// Auto-generated by compile_library.jl — do not edit by hand
#ifndef JG_STATIC_H
#define JG_STATIC_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Returns 1 if mouse is inside element rect, else 0. */
/* element_right = element_x + width, element_bottom = element_y + height */
int32_t static_is_mouse_inside_element(
    int32_t mouse_x, int32_t mouse_y,
    int32_t element_x, int32_t element_y,
    int32_t element_right, int32_t element_bottom);

/* First 1-based hit index in layer order, or -1. Arrays length n. */
int32_t static_ui_hit_test_batch(
    int32_t mouse_x, int32_t mouse_y,
    const int32_t *xs, const int32_t *ys,
    const int32_t *rights, const int32_t *bottoms,
    int32_t n);

#ifdef __cplusplus
}
#endif

#endif /* JG_STATIC_H */
