# Build lib_desktop/libsc_game.so from Julia (no SDL).
# Pattern: sc-game/compile_library.jl — functions list + .o merge + shared lib only.
#
# Usage (from this directory):
#   julia --project=. compile_library.jl desktop
#   ./build_host.sh
#
# Needs Julia 1.11 + StaticCompiler from this folder's Project.toml (not global 0.7.2).

using Pkg
const STATIC_ROOT = @__DIR__
if isfile(joinpath(STATIC_ROOT, "Project.toml"))
    Pkg.activate(STATIC_ROOT)
    Pkg.instantiate()
end

using StaticTools
using StaticCompiler

compile_file = get(ENV, "FILE", "library.jl")
include(joinpath(STATIC_ROOT, compile_file))

build_type = length(ARGS) > 0 ? lowercase(ARGS[1]) : "desktop"
build_type in ("web", "desktop") || error("Usage: julia --project=. compile_library.jl [web|desktop]")

lib_base = get(ENV, "LIB_NAME", "sc_game")
output_dir = build_type == "web" ? "lib_wasm" : "lib_desktop"
isdir(output_dir) || mkdir(output_dir)

println("📚 Compiling Julia library for $build_type")
println("   Julia $(VERSION.major).$(VERSION.minor).$(VERSION.patch)")
println("   StaticCompiler $(pkgversion(StaticCompiler))")
println("=" ^ 50)

println("🧹 Cleaning up old files...")
for file in readdir(output_dir)
    if endswith(file, ".ll") || endswith(file, ".o") || endswith(file, ".so") ||
       endswith(file, ".dll") || endswith(file, ".dylib") || endswith(file, ".a") || endswith(file, ".h")
        rm(joinpath(output_dir, file))
        println("🗑️  Removed: $file")
    end
end

const _BATCH_SIG = (
    Int32, Int32,
    Ptr{Int32}, Ptr{Int32}, Ptr{Int32}, Ptr{Int32},
    Int32,
)

functions_to_compile = [
    (static_is_mouse_inside_element, (Int32, Int32, Int32, Int32, Int32, Int32), "static_is_mouse_inside_element"),
    (static_ui_hit_test_batch, _BATCH_SIG, "static_ui_hit_test_batch"),
]

compile_ok = true
for (func, types, name) in functions_to_compile
    println(" Compiling $name...")
    try
        if build_type == "web"
            StaticCompiler.generate_obj(func, types, output_dir, name, emit_llvm_only=true)
            println("✅ Generated: $output_dir/$name.ll")
        else
            StaticCompiler.generate_obj(func, types, output_dir, name, emit_llvm_only=false)
            println("✅ Generated: $output_dir/$name.o")
        end
    catch e
        global compile_ok = false
        println("❌ Error compiling $name: $e")
        if occursin("validate_code_in_debug_mode", string(e))
            println("💡 Use: julia --project=$(STATIC_ROOT) compile_library.jl desktop")
            println("   (global StaticCompiler 0.7.2 does not support Julia 1.11)")
        end
    end
end

function write_c_header(path::String)
    open(path, "w") do io
        println(io, "// Auto-generated by compile_library.jl — do not edit by hand")
        println(io, "#ifndef SC_GAME_H")
        println(io, "#define SC_GAME_H")
        println(io, "")
        println(io, "#include <stdint.h>")
        println(io, "")
        println(io, "#ifdef __cplusplus")
        println(io, "extern \"C\" {")
        println(io, "#endif")
        println(io, "")
        println(io, "/* Returns 1 if mouse is inside element rect, else 0. */")
        println(io, "/* element_right = element_x + width, element_bottom = element_y + height */")
        println(io, "int32_t static_is_mouse_inside_element(")
        println(io, "    int32_t mouse_x, int32_t mouse_y,")
        println(io, "    int32_t element_x, int32_t element_y,")
        println(io, "    int32_t element_right, int32_t element_bottom);")
        println(io, "")
        println(io, "/* First 1-based hit index in layer order, or -1. Arrays length n. */")
        println(io, "int32_t static_ui_hit_test_batch(")
        println(io, "    int32_t mouse_x, int32_t mouse_y,")
        println(io, "    const int32_t *xs, const int32_t *ys,")
        println(io, "    const int32_t *rights, const int32_t *bottoms,")
        println(io, "    int32_t n);")
        println(io, "")
        println(io, "#ifdef __cplusplus")
        println(io, "}")
        println(io, "#endif")
        println(io, "")
        println(io, "#endif /* SC_GAME_H */")
    end
end

header_path = joinpath(output_dir, "$(lib_base).h")
write_c_header(header_path)
println("✅ Generated C header: $header_path")

if build_type == "web"
    println("\n⚠️  Web/WASM build not set up in JulGame Static yet.")
    println("   For emscripten + SDL, see sc-game/compile_library.jl web target.")
    compile_ok || exit(1)
    exit(0)
end

if !compile_ok
    println("\n❌ One or more functions failed to compile — not linking.")
    exit(1)
end

run_cmd(exe::String, args::Vector{String}) = run(Cmd(vcat([exe], args)))

println("\n🔨 Bundling native library (Julia .o only, no SDL)...")

julia_o_files = String[]
for file in readdir(output_dir)
    endswith(file, ".o") && push!(julia_o_files, joinpath(output_dir, file))
end

if isempty(julia_o_files)
    println("❌ No .o files in $output_dir — compile step produced nothing.")
    exit(1)
end

merged_o = joinpath(output_dir, "$(lib_base)_merged.o")
opt_c = ["-O3", "-flto", "-fPIC"]
if length(julia_o_files) == 1
    cp(julia_o_files[1], merged_o; force=true)
else
    run_cmd("gcc", vcat(opt_c, ["-r", "-o", merged_o], julia_o_files))
end

static_lib = joinpath(output_dir, "lib$(lib_base).a")
run_cmd("ar", ["rcs", static_lib, merged_o])
println("✅ Static archive: $static_lib")

if Sys.iswindows()
    lib_name = "$(lib_base).dll"
    system_libs = String[]
elseif Sys.isapple()
    lib_name = "lib$(lib_base).dylib"
    system_libs = ["-Wl,-undefined,dynamic_lookup"]
else
    lib_name = "lib$(lib_base).so"
    system_libs = ["-ldl", "-lpthread", "-lm"]
end

lib_path = joinpath(output_dir, lib_name)
soname = Sys.islinux() ? ["-Wl,-soname,$lib_name"] : String[]
run_cmd("gcc", vcat(["-shared"], opt_c, soname, ["-o", lib_path, merged_o], system_libs))
println("✅ Shared library: $lib_path")
println("\n💡 Verify: ./build_host.sh")
