using StaticTools
using StaticCompiler

compile_file = get(ENV, "FILE", "library.jl")
include(compile_file)

build_type = "desktop"
if length(ARGS) > 0
    build_type = lowercase(ARGS[1])
    if build_type != "web" && build_type != "desktop"
        println("❌ Error: Build type must be 'web' or 'desktop'")
        println("Usage: julia compile_library.jl [web|desktop]")
        exit(1)
    end
end

lib_base = get(ENV, "LIB_NAME", "sc_game")
output_dir = build_type == "web" ? "lib_wasm" : "lib_desktop"

println("📚 Compiling Julia library for $build_type")
println("=" ^ 50)

if !isdir(output_dir)
    mkdir(output_dir)
end

println("🧹 Cleaning up old files...")
for file in readdir(output_dir)
    if endswith(file, ".ll") || endswith(file, ".js") || endswith(file, ".wasm") ||
       endswith(file, ".o") || endswith(file, ".so") || endswith(file, ".dll") ||
       endswith(file, ".dylib") || endswith(file, ".a") || endswith(file, ".h")
        rm(joinpath(output_dir, file))
        println("🗑️  Removed: $file")
    end
end

functions_to_compile = [
    (static_is_mouse_inside_element, (Int32, Int32, Int32, Int32, Int32, Int32), "static_is_mouse_inside_element"),
]

for (func, types, name) in functions_to_compile
    try
        println(" Compiling $name...")
        if build_type == "web"
            StaticCompiler.generate_obj(func, types, output_dir, name, emit_llvm_only=true)
            println("✅ Generated: $output_dir/$name.ll")
        else
            StaticCompiler.generate_obj(func, types, output_dir, name, emit_llvm_only=false)
            println("✅ Generated: $output_dir/$name.o")
        end
    catch e
        println("❌ Error compiling $name: $e")
    end
end

function write_c_header(path::String)
    open(path, "w") do io
        println(io, "// Auto-generated by compile_library.jl — do not edit by hand")
        println(io, "#include <stdint.h>")
        println(io, "")
        println(io, "bool static_is_mouse_inside_element(int32_t mouse_x, int32_t mouse_y, int32_t element_x, int32_t element_y, int32_t element_width, int32_t element_height);")
        println(io, "")
    end
end

header_path = joinpath(output_dir, "$(lib_base).h")
write_c_header(header_path)
println("✅ Generated C header: $header_path")

if build_type == "web"
    println("\n🔨 Linking framework WebAssembly (engine + host.c)...")

    game_wasm_dir = "game_wasm"
    if !isdir(game_wasm_dir)
        mkdir(game_wasm_dir)
    end

    try
        ll_files = String[]
        for file in readdir(output_dir)
            if endswith(file, ".ll")
                push!(ll_files, joinpath(output_dir, file))
            end
        end

        combined_ll = joinpath(output_dir, "combined.ll")
        llvm_link_cmd = `llvm-link -S -o $combined_ll $ll_files`
        ll_input = ll_files
        try
            run(llvm_link_cmd)
            combined_content = read(combined_ll, String)
            combined_content = replace(combined_content, r"target triple = \"[^\"]+\"" => "target triple = \"wasm32-unknown-emscripten\"")
            write(combined_ll, combined_content)
            ll_input = combined_ll
            println("✅ Combined LLVM IR: $combined_ll")
        catch e
            println("⚠️  llvm-link failed, using separate .ll files: $e")
        end

        host_c = joinpath(@__DIR__, "host.c")
        isfile(host_c) || error("Missing host.c at $host_c")

        game_js = joinpath(game_wasm_dir, "game.js")
        cmd = `emcc $ll_input SDLCalls/sdl_module.c $host_c -DSC_HOST_MAIN -I$output_dir -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["png"]' -s USE_SDL_MIXER=2 -s USE_OGG=1 -s USE_WEBGL2=1 -O2 -s WASM=1 -s
        EXPORTED_FUNCTIONS="['_main','_malloc','_free','_sc_engine_init','_sc_frame','_sc_engine_shutdown']"
        -s EXPORTED_RUNTIME_METHODS="['cwrap']"
        -s ALLOW_MEMORY_GROWTH=1
        -s INITIAL_MEMORY=33554432
        -s ALLOW_TABLE_GROWTH=1
        -s STACK_SIZE=1048576
        -o $game_js
        --preload-file ./assets
        --use-preload-plugins`
        run(cmd)
        println("✅ Framework WebAssembly: $game_js")
        println("   - $(game_wasm_dir)/game.wasm")

        game_data = joinpath(game_wasm_dir, "game.data")
        if isfile(game_data)
            cp(game_data, "./game.data"; force=true)
            println("✅ Copied game.data to repo root")
        end

        println("💡 Serve the repo root and open index.html (e.g. python3 -m http.server)")
    catch e
        println("❌ Web library build failed: $e")
        rethrow()
    end

else
    function pkg_config_flags(args::String...)::Vector{String}
        out = readchomp(Cmd(vcat(["pkg-config"], collect(args))))
        return isempty(out) ? String[] : split(out, isspace; keepempty=false)
    end

    # Backtick Cmd merges adjacent `-l`/`-L` flags (e.g. `-lSDL2` + `-ldl` → `-lSDL2-ldl`).
    run_cmd(exe::String, args::Vector{String}) = run(Cmd(vcat([exe], args)))

    println("\n🔨 Bundling portable native library...")

    try
        julia_o_files = String[]
        for file in readdir(output_dir)
            if endswith(file, ".o") && !startswith(file, "sdl_module")
                push!(julia_o_files, joinpath(output_dir, file))
            end
        end

        sdl_module_o = joinpath(output_dir, "sdl_module.o")
        sdl2_pc = if isdir(joinpath(@__DIR__, "deps", "sdl2", "prefix", "lib64", "pkgconfig"))
            joinpath(@__DIR__, "deps", "sdl2", "prefix", "lib64", "pkgconfig")
        elseif isdir(joinpath(@__DIR__, "deps", "sdl2", "prefix", "lib", "pkgconfig"))
            joinpath(@__DIR__, "deps", "sdl2", "prefix", "lib", "pkgconfig")
        else
            ""
        end
        sdl_cflags = if !isempty(sdl2_pc)
            withenv("PKG_CONFIG_PATH" => sdl2_pc * (haskey(ENV, "PKG_CONFIG_PATH") ? ":" * ENV["PKG_CONFIG_PATH"] : "")) do
                pkg_config_flags("--cflags", "sdl2")
            end
        else
            pkg_config_flags("--cflags", "sdl2")
        end
        run_cmd("gcc", vcat(["-c", "-fPIC", "-O2", "SDLCalls/sdl_module.c", "-o", sdl_module_o], sdl_cflags))

        merged_o = joinpath(output_dir, "$(lib_base)_merged.o")
        run_cmd("ld", vcat(["-r", "-o", merged_o], julia_o_files, [sdl_module_o]))

        sdl_shared = pkg_config_flags("--libs", "sdl2")
        static_lib = joinpath(output_dir, "lib$(lib_base).a")
        # Julia-only archive — SDL is linked at host build time (see build_host.sh).
        # Fedora's libSDL2.a is sdl2-compat and dlopens libSDL3 at runtime; baking it in breaks portable zips.
        run_cmd("ar", ["rcs", static_lib, merged_o])
        println("✅ Static archive (Julia only): $static_lib")
        bundle_mode = "host-links-sdl"

        if Sys.iswindows()
            lib_name = "$(lib_base).dll"
            system_libs = String[]
        elseif Sys.isapple()
            lib_name = "lib$(lib_base).dylib"
            # game_* hooks live in the host executable; ELF .so allows undefined refs,
            # but macOS dylib link fails unless we defer resolution to load time.
            system_libs = ["-Wl,-undefined,dynamic_lookup"]
        else
            lib_name = "lib$(lib_base).so"
            system_libs = ["-ldl", "-lpthread", "-lm"]
        end

        lib_path = joinpath(output_dir, lib_name)
        soname = Sys.islinux() ? ["-Wl,-soname,$lib_name"] : String[]
        # libSDL2.a is not built with -fPIC on Fedora, so it cannot go inside a .so.
        # Static bundle → libsc_game.a only; .so always uses shared SDL2.
        run_cmd("gcc", vcat(["-shared", "-fPIC", "-O2"], soname, ["-o", lib_path, merged_o], sdl_shared, system_libs))
        if bundle_mode != "static"
            bundle_mode = "shared"
        end
        println("✅ Shared library: $lib_path (SDL2 shared dep, no -lSDL2 at host link time)")

        println()
        println("💡 Build C host: ./build_host.sh")
        println("   Package zip:  ./package_host.sh")
        println("   # main() in host.c calls sc_run(); game hooks live in host.c.")
    catch e
        println("❌ Native library build failed: $e")
        if Sys.islinux()
            println("💡 Install: sudo dnf install SDL2-devel pkg-config  (Fedora)")
        end
    end
end

println("\n✅ Library build complete for $(build_type)!")
