# Declare Common Functions so that they can be dispatched from ModuleExtensions
import ..JulGame: add_collision_event,
    apply_effects!,
    check_collisions,
    destroy,
    draw,
    duplicate,
    flip,
    get_position,
    get_rotation,
    get_scale,
    get_size,
    initialize,
    is_mouse_hovering,
    load_image,
    load_sound,
    play,
    play_animation_once,
    render,
    set_color,
    set_position,
    set_rotation,
    set_scale,
    set_size,
    set_volume,
    stop_music,
    toggle_sound,
    unload_sound,
    update

