println("precompiling")
precompile(Tuple{typeof(include), String})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, NamedTuple{(:pos, :active, :index), Tuple{Int64, Bool, Int64}}, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, Array{NamedTuple{(:label, :value), Tuple{Symbol, Any}}, 1}, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{typeof(Base.:(==)), Bool, Bool})
precompile(Tuple{Type{Base.Generator{I, F} where F where I}, typeof(Base.identity), Tuple{Array{String, 1}}})
precompile(Tuple{typeof(Base._xfadjoint_unwrap), Base.Generator{Tuple{Array{String, 1}}, typeof(Base.identity)}})
precompile(Tuple{typeof(Base.getproperty), Base.Generator{Tuple{Array{String, 1}}, typeof(Base.identity)}, Symbol})
precompile(Tuple{typeof(Base._xfadjoint_unwrap), Tuple{Array{String, 1}}})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Tuple{Array{String, 1}}, typeof(Base.identity)}, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Tuple{Array{String, 1}}, typeof(Base.identity)}, Int64, Int64})
precompile(Tuple{typeof(Base.vect), Array{String, 1}, Vararg{Array{String, 1}}})
precompile(Tuple{typeof(Base.iterate), Array{Array{String, 1}, 1}})
precompile(Tuple{Type{Ref{Any}}, Ptr{Nothing}})
precompile(Tuple{typeof(Editor.include), String})
precompile(Tuple{typeof(Core.kwcall), NamedTuple{(:join,), Tuple{Bool}}, typeof(Base.Filesystem.readdir), String})
precompile(Tuple{typeof(Base.filter), Base.Fix2{typeof(Base.contains), Base.Regex}, Array{String, 1}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted), typeof(Editor.include), Array{String, 1}})
precompile(Tuple{typeof(Base.Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(Editor.include), Tuple{Array{String, 1}}}})
precompile(Tuple{Base.var"#4#5"{Base.var"#1065#1066"}, Tuple{Symbol, Nothing}})
precompile(Tuple{typeof(Base._array_for), Type{Symbol}, Base.HasShape{1}, Tuple{Base.OneTo{Int64}}})
precompile(Tuple{typeof(Base.collect_to_with_first!), Array{Symbol, 1}, Symbol, Base.Generator{Base.Iterators.Zip{Tuple{Array{Any, 1}, Array{Any, 1}}}, Base.var"#4#5"{Base.var"#1065#1066"}}, Tuple{Int64, Int64}})
precompile(Tuple{typeof(Base.isempty), Array{Symbol, 1}})
precompile(Tuple{typeof(Base.string), Expr})
precompile(Tuple{typeof(Base.getindex), Array{Any, 1}})
precompile(Tuple{typeof(Base.gensym), String})
precompile(Tuple{Type{Pair{A, B} where B where A}, UInt32, CImGui.lib.ImGuiKey})
precompile(Tuple{Type{Base.Dict{K, V} where V where K}, Pair{UInt32, CImGui.lib.ImGuiKey}, Vararg{Pair{UInt32, CImGui.lib.ImGuiKey}}})
precompile(Tuple{Type{Base.Dict{UInt32, CImGui.lib.ImGuiKey}}, NTuple{119, Pair{UInt32, CImGui.lib.ImGuiKey}}})
precompile(Tuple{typeof(Base.similar), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Type{Base.Dict{UInt32, CImGui.lib.ImGuiKey}}})
precompile(Tuple{typeof(Base.setindex!), Array{Base.Dict{UInt32, CImGui.lib.ImGuiKey}, 1}, Base.Dict{UInt32, CImGui.lib.ImGuiKey}, Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!), Array{Base.Dict{UInt32, CImGui.lib.ImGuiKey}, 1}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Base.OneTo{Int64}, Int64, Int64})
precompile(Tuple{Base.var"#4#5"{Base.var"#1065#1066"}, Tuple{Symbol, Expr}})
precompile(Tuple{typeof(Base.CoreLogging.logmsg_code), Any, Any, Any, Any, Any, Any, Vararg{Any}})
precompile(Tuple{typeof(Base.CoreLogging.process_logmsg_exs), Any, Any, Any, Any, Any, Any, Vararg{Any}})
precompile(Tuple{typeof(Base.join), Tuple{Symbol, Symbol, Symbol}, String})
precompile(Tuple{typeof(Base.join), Base.GenericIOBuffer{GenericMemory{:not_atomic, UInt8, Core.AddrSpace{Core}(0x00)}}, Tuple{Symbol, Symbol, Symbol}, String})
precompile(Tuple{typeof(Base.print), Base.GenericIOBuffer{GenericMemory{:not_atomic, UInt8, Core.AddrSpace{Core}(0x00)}}, Tuple{Expr}})
precompile(Tuple{typeof(Base.show_call), Base.IOContext{Base.GenericIOBuffer{GenericMemory{:not_atomic, UInt8, Core.AddrSpace{Core}(0x00)}}}, Symbol, Expr, Array{Any, 1}, Int64, Int64, Bool})
precompile(Tuple{typeof(Base.similar), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Type{Any}})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!), Array{Any, 1}, Array{Base.Dict{UInt32, CImGui.lib.ImGuiKey}, 1}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Function, Int64, Base.OneTo{Int64}, Int64, Int64})
precompile(Tuple{typeof(Base.first), Tuple{Expr}})
precompile(Tuple{typeof(Base.eval), Module, Expr})
precompile(Tuple{typeof(Base.similar), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Type{typeof(Editor.show_camera_window)}})
precompile(Tuple{typeof(Base.setindex!), Array{typeof(Editor.show_camera_window), 1}, Function, Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!), Array{typeof(Editor.show_camera_window), 1}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Base.OneTo{Int64}, Int64, Int64})
precompile(Tuple{typeof(Base.Docs.docm), LineNumberNode, Module, Any, Any})
precompile(Tuple{typeof(Base.CoreLogging.logmsg_code), Vararg{Any, 5}})
precompile(Tuple{typeof(Base.print), Base.GenericIOBuffer{GenericMemory{:not_atomic, UInt8, Core.AddrSpace{Core}(0x00)}}, Expr})
precompile(Tuple{typeof(Base.similar), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Type{Function}})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!), Array{Function, 1}, Array{typeof(Editor.show_camera_window), 1}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Function, Int64, Base.OneTo{Int64}, Int64, Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!), Array{Function, 1}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Base.OneTo{Int64}, Int64, Int64})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!), Array{Any, 1}, Array{Function, 1}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Base.Docs.Binding, Int64, Base.OneTo{Int64}, Int64, Int64})
precompile(Tuple{typeof(Base.CoreLogging.shouldlog), Base.CoreLogging.ConsoleLogger, Base.CoreLogging.LogLevel, Module, Symbol, Symbol})
precompile(Tuple{typeof(Base.get), Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Symbol, Nothing})
precompile(Tuple{typeof(Base.CoreLogging.handle_message), Base.CoreLogging.ConsoleLogger, Base.CoreLogging.LogLevel, Vararg{Any, 6}})
precompile(Tuple{typeof(Base.convert), Type{String}, String})
precompile(Tuple{typeof(Base.isopen), Base.GenericIOBuffer{GenericMemory{:not_atomic, UInt8, Core.AddrSpace{Core}(0x00)}}})
precompile(Tuple{Type{NamedTuple{(:segments,), T} where T<:Tuple}, Tuple{Tuple{String}}})
precompile(Tuple{typeof(Base.CoreLogging.default_metafmt), Base.CoreLogging.LogLevel, Vararg{Any, 5}})
precompile(Tuple{typeof(Base.string), Module})
precompile(Tuple{typeof(Base.Filesystem.contractuser), String})
precompile(Tuple{Type{Base.IOContext{IO_t} where IO_t<:IO}, Base.GenericIOBuffer{GenericMemory{:not_atomic, UInt8, Core.AddrSpace{Core}(0x00)}}, Base.TTY})
precompile(Tuple{typeof(Base.write), Base.TTY, Array{UInt8, 1}})
precompile(Tuple{Type{Pair{A, B} where B where A}, String, Array{String, 1}})
precompile(Tuple{Type{Base.Dict{K, V} where V where K}, Pair{String, Array{String, 1}}, Vararg{Pair{String, Array{String, 1}}}})
precompile(Tuple{Type{Base.Dict{String, Array{String, 1}}}, NTuple{4, Pair{String, Array{String, 1}}}})
precompile(Tuple{typeof(Base.first), Tuple{Expr, Expr}})
precompile(Tuple{typeof(Base.literal_pow), typeof(Base.:(^)), String, Base.Val{128}})
precompile(Tuple{typeof(Base.similar), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Type{Base.Docs.Binding}})
precompile(Tuple{typeof(Base.setindex!), Array{Base.Docs.Binding, 1}, Base.Docs.Binding, Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!), Array{Base.Docs.Binding, 1}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Base.OneTo{Int64}, Int64, Int64})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!), Array{Any, 1}, Array{Base.Docs.Binding, 1}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Function, Int64, Base.OneTo{Int64}, Int64, Int64})
precompile(Tuple{Type{Editor.PaletteId}, Int32})
precompile(Tuple{Type{Editor.LanguageDefinitionId}, Int32})
precompile(Tuple{Type{Editor.SetViewAtLineMode}, Int32})
precompile(Tuple{Type{Editor.MoveDirection}, Int32})
precompile(Tuple{Type{Editor.UndoOperationType}, Int32})
precompile(Tuple{Type{Editor.PaletteIndex}, Int32})
precompile(Tuple{typeof(Base.vect), UInt32, Vararg{UInt32}})
precompile(Tuple{Type{Pair{A, B} where B where A}, Editor.PaletteId, Array{UInt32, 1}})
precompile(Tuple{Type{Base.Dict{Editor.PaletteId, Array{UInt32, 1}}}, Pair{Editor.PaletteId, Array{UInt32, 1}}, Vararg{Pair{Editor.PaletteId, Array{UInt32, 1}}}})
precompile(Tuple{typeof(Base.iterate), Base.CodeUnits{UInt8, String}})
precompile(Tuple{typeof(Base.iterate), Base.CodeUnits{UInt8, String}, Int64})
precompile(Tuple{Type{Printf.Format{S, T} where T where S}, String})
precompile(Tuple{typeof(Base.similar), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Type{typeof(Editor.show)}})
precompile(Tuple{typeof(Base.setindex!), Array{typeof(Editor.show), 1}, Function, Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!), Array{typeof(Editor.show), 1}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Base.OneTo{Int64}, Int64, Int64})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!), Array{Function, 1}, Array{typeof(Editor.show), 1}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Function, Int64, Base.OneTo{Int64}, Int64, Int64})
precompile(Tuple{typeof(Base.join), NTuple{4, Symbol}, String})
precompile(Tuple{typeof(Base.join), Base.GenericIOBuffer{GenericMemory{:not_atomic, UInt8, Core.AddrSpace{Core}(0x00)}}, NTuple{4, Symbol}, String})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!), Array{Any, 1}, Array{Function, 1}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Module, Int64, Base.OneTo{Int64}, Int64, Int64})
precompile(Tuple{typeof(Editor.CodeEditorModule.include), String})
precompile(Tuple{Type{Editor.CodeEditorModule.PaletteId}, Int32})
precompile(Tuple{Type{Editor.CodeEditorModule.LanguageDefinitionId}, Int32})
precompile(Tuple{Type{Editor.CodeEditorModule.SetViewAtLineMode}, Int32})
precompile(Tuple{Type{Editor.CodeEditorModule.MoveDirection}, Int32})
precompile(Tuple{Type{Editor.CodeEditorModule.UndoOperationType}, Int32})
precompile(Tuple{Type{Editor.CodeEditorModule.PaletteIndex}, Int32})
precompile(Tuple{Type{Pair{A, B} where B where A}, Editor.CodeEditorModule.PaletteId, Array{UInt32, 1}})
precompile(Tuple{Type{Base.Dict{Editor.CodeEditorModule.PaletteId, Array{UInt32, 1}}}, Pair{Editor.CodeEditorModule.PaletteId, Array{UInt32, 1}}, Vararg{Pair{Editor.CodeEditorModule.PaletteId, Array{UInt32, 1}}}})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, Editor.CodeEditorModule.Glyph, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, Editor.CodeEditorModule.UndoRecord, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{Type{CImGui.lib.ImVec2}, Int64, Int64})
precompile(Tuple{typeof(Base.keys), Base.Dict{Editor.CodeEditorModule.PaletteId, Array{UInt32, 1}}})
precompile(Tuple{typeof(Base.getproperty), Base.KeySet{Editor.CodeEditorModule.PaletteId, Base.Dict{Editor.CodeEditorModule.PaletteId, Array{UInt32, 1}}}, Symbol})
precompile(Tuple{Type{Editor.CodeEditorModule.CodeEditorWindow}})
precompile(Tuple{typeof(Base.join), Base.GenericIOBuffer{GenericMemory{:not_atomic, UInt8, Core.AddrSpace{Core}(0x00)}}, Array{Char, 1}})
precompile(Tuple{typeof(Base.similar), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Type{Module}})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!), Array{Module, 1}, Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(Editor.include), Tuple{Base.Broadcast.Extruded{Array{String, 1}, Tuple{Bool}, Tuple{Int64}}}}, Base.OneTo{Int64}, Int64, Int64})
precompile(Tuple{typeof(Base.:(|)), JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_WindowFlags, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_WindowFlags})
precompile(Tuple{typeof(Base.:(|)), UInt32, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_WindowFlags})
precompile(Tuple{typeof(Base.cconvert), Type{UInt32}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RendererFlags})
precompile(Tuple{Type{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_version}, Int64, Int64, Int64})
precompile(Tuple{Type{Int64}, Char})
precompile(Tuple{typeof(Base.:(-)), Int32, Int32})
precompile(Tuple{typeof(Base.cconvert), Type{Ptr{CImGui.lib.ImFontAtlas}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Ptr{CImGui.lib.ImFontAtlas}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.cconvert), Type{Ptr{CImGui.lib.ImFontConfig}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Ptr{CImGui.lib.ImFontConfig}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.cconvert), Type{Ptr{UInt16}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Ptr{UInt16}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Float32}, Float32})
precompile(Tuple{typeof(Base.convert), Type{Ptr{Nothing}}, Ptr{Nothing}})
precompile(Tuple{Type{Ptr{Any}}, Ptr{Nothing}})
precompile(Tuple{Type{Ptr{Nothing}}, Ptr{Nothing}})
precompile(Tuple{Type{Ptr{Int8}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.convert), Type{Ptr{Any}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.cconvert), Type, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_SystemCursor})
precompile(Tuple{typeof(Base.unsafe_convert), Type{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_SystemCursor}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_SystemCursor})
precompile(Tuple{typeof(Base.:(+)), CImGui.lib.ImGuiMouseCursor_, Int64})
precompile(Tuple{typeof(Base.convert), Type{Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Texture}}, Ptr{Nothing}})
precompile(Tuple{Type{Ptr{UInt8}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.convert), Type{Int32}, CImGui.lib.ImFontAtlasFlags_})
precompile(Tuple{typeof(Base.cconvert), Type{UInt32}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_PixelFormatEnum})
precompile(Tuple{typeof(Base.cconvert), Type{Int32}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_TextureAccess})
precompile(Tuple{typeof(Base.cconvert), Type{Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Rect}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Rect}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.cconvert), Type, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_BlendMode})
precompile(Tuple{typeof(Base.unsafe_convert), Type{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_BlendMode}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_BlendMode})
precompile(Tuple{typeof(Base.cconvert), Type, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_ScaleMode})
precompile(Tuple{typeof(Base.unsafe_convert), Type{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_ScaleMode}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_ScaleMode})
precompile(Tuple{typeof(Base.convert), Type{Float32}, Float64})
precompile(Tuple{typeof(Base.getproperty), CImGui.lib.ImVec2, Symbol})
precompile(Tuple{Type{CImGui.lib.ImVec2}, Float32, Float32})
precompile(Tuple{typeof(Base.cconvert), Type{Ptr{CImGui.lib.ImGuiStyle}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Ptr{CImGui.lib.ImGuiStyle}}, Ptr{Nothing}})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, JulGame.EntityModule.Entity, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{Type{CImGui.lib.ImVec2}, Float64, Float64})
precompile(Tuple{Type{NamedTuple{(:message, :confirmText, :cancelText, :open, :type), T} where T<:Tuple}, Tuple{String, String, String, Bool, String}})
precompile(Tuple{typeof(Base.clamp), Int64, Int64, Int64})
precompile(Tuple{typeof(Base.floor), Int64})
precompile(Tuple{Type{Bool}, Int64})
precompile(Tuple{Type{NamedTuple{(:read, :write, :append, :truncate), T} where T<:Tuple}, Tuple{Bool, Bool, Nothing, Nothing}})
precompile(Tuple{Dates.var"##s53#31", Vararg{Any, 5}})
precompile(Tuple{Base.var"##s128#278", Vararg{Any, 5}})
precompile(Tuple{Type{UInt32}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_EventType})
precompile(Tuple{typeof(Base.cconvert), Type, CImGui.lib.ImGuiKey})
precompile(Tuple{typeof(Base.unsafe_convert), Type{CImGui.lib.ImGuiKey}, CImGui.lib.ImGuiKey})
precompile(Tuple{Type{UInt32}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_WindowEventID})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Bool}, Bool})
precompile(Tuple{Type{Int32}, CImGui.lib.ImGuiMouseCursor_})
precompile(Tuple{typeof(Base.cconvert), Type{Int32}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_bool})
precompile(Tuple{typeof(Base.cconvert), Type{Int32}, CImGui.lib.ImGuiCol_})
precompile(Tuple{typeof(Base.cconvert), Type, NTuple{4, Float64}})
precompile(Tuple{typeof(Base.convert), Type{CImGui.lib.ImVec4}, NTuple{4, Float64}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{CImGui.lib.ImVec4}, CImGui.lib.ImVec4})
precompile(Tuple{typeof(Base.convert), Type{UInt32}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.cconvert), Type{Ptr{CImGui.lib.ImGuiViewport}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.cconvert), Type{Int32}, CImGui.lib.ImGuiDockNodeFlags_})
precompile(Tuple{typeof(Base.cconvert), Type{Ptr{CImGui.lib.ImGuiWindowClass}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Ptr{CImGui.lib.ImGuiViewport}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Ptr{CImGui.lib.ImGuiWindowClass}}, Ptr{Nothing}})
precompile(Tuple{Type{CImGui.lib.ImGuiHoveredFlags_}, Int64})
precompile(Tuple{typeof(Base.cconvert), Type{Int32}, CImGui.lib.ImGuiHoveredFlags_})
precompile(Tuple{typeof(Base.cconvert), Type{Ptr{Int8}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Ptr{Int8}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.cconvert), Type{Int32}, CImGui.lib.ImGuiWindowFlags_})
precompile(Tuple{typeof(Base.cconvert), Type{Ptr{Int8}}, String})
precompile(Tuple{typeof(Base.:(|)), CImGui.lib.ImGuiWindowFlags_, CImGui.lib.ImGuiWindowFlags_})
precompile(Tuple{typeof(Base.:(|)), UInt32, CImGui.lib.ImGuiWindowFlags_})
precompile(Tuple{typeof(Base.convert), Type{Int32}, UInt32})
precompile(Tuple{typeof(Base.cconvert), Type{Int32}, CImGui.lib.ImGuiFocusedFlags_})
precompile(Tuple{Type{UInt32}, CImGui.lib.ImGuiKey})
precompile(Tuple{Type{UInt16}, Char})
precompile(Tuple{typeof(Base.cconvert), Type{Int32}, CImGui.lib.ImGuiMouseButton_})
precompile(Tuple{Type{Int64}, Editor.CodeEditorModule.PaletteIndex})
precompile(Tuple{typeof(Base.cconvert), Type, Float64})
precompile(Tuple{typeof(Base.cconvert), Type{Int32}, CImGui.lib.ImDrawFlags_})
precompile(Tuple{typeof(Base.:(>=)), Float64, Float64})
precompile(Tuple{typeof(Base.cconvert), Type, Float32})
precompile(Tuple{typeof(Base.cconvert), Type, Tuple{Int64, Int64}})
precompile(Tuple{typeof(Base.convert), Type{CImGui.lib.ImVec2}, Tuple{Int64, Int64}})
precompile(Tuple{typeof(Base.cconvert), Type{Int32}, CImGui.lib.ImGuiCond_})
precompile(Tuple{typeof(Base.unsafe_convert), Type{CImGui.lib.ImVec2}, CImGui.lib.ImVec2})
precompile(Tuple{typeof(Base.cconvert), Type{Int32}, CImGui.lib.ImGuiStyleVar_})
precompile(Tuple{typeof(Base.cconvert), Type, CImGui.lib.ImVec2})
precompile(Tuple{Type{CImGui.lib.ImGuiDragDropFlags_}, Int64})
precompile(Tuple{typeof(Base.cconvert), Type{Int32}, CImGui.lib.ImGuiDragDropFlags_})
precompile(Tuple{Type{CImGui.lib.ImGuiCond_}, Int64})
precompile(Tuple{typeof(Base.cconvert), Type{Ptr{Bool}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Ptr{Bool}}, Ptr{Nothing}})
precompile(Tuple{Type{Pair{A, B} where B where A}, Base.Regex, String})
precompile(Tuple{typeof(Base.isempty), Base.UnitRange{Int64}})
precompile(Tuple{typeof(Base.cconvert), Type, UInt16})
precompile(Tuple{typeof(Base.unsafe_convert), Type{UInt16}, UInt16})
precompile(Tuple{typeof(Base.convert), Type{UInt32}, UInt64})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, JulGame.UI.TextBoxModule.TextBox, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{typeof(Base.convert), Type{Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Window}}, Ptr{Nothing}})
precompile(Tuple{Type{JulGame.SimpleDirectMediaLayer.LibSDL2.FPSmanager}, UInt32, Float32, UInt32, UInt32, UInt32})
precompile(Tuple{Type{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_DisplayMode}, UInt32, Int64, Int64, Int64, Ptr{Nothing}})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, JulGame.Component.AnimationModule.Animation, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{typeof(Base.:(==)), Symbol, Symbol})
precompile(Tuple{Type{NamedTuple{(:own,), T} where T<:Tuple}, Tuple{Bool}})
precompile(Tuple{typeof(Base.sym_in), Symbol, NTuple{18, Symbol}})
precompile(Tuple{typeof(Base.Iterators.enumerate), NTuple{14, Symbol}})
precompile(Tuple{typeof(Base.iterate), Base.Iterators.Enumerate{NTuple{14, Symbol}}})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Int64, Symbol}, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Int64, Symbol}, Int64, Int64})
precompile(Tuple{typeof(Base.iterate), Base.Iterators.Enumerate{NTuple{14, Symbol}}, Tuple{Int64, Int64}})
precompile(Tuple{Type{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Color}, Vararg{Int64, 4}})
precompile(Tuple{typeof(Base.:(!=)), UInt64, UInt64})
precompile(Tuple{typeof(Base.:(|)), UInt64, UInt64})
precompile(Tuple{typeof(Base.:(*)), UInt64, UInt64})
precompile(Tuple{typeof(Base.signed), UInt64})
precompile(Tuple{typeof(Base.:(>)), UInt64, UInt64})
precompile(Tuple{Type{NamedTuple{(:precision,), T} where T<:Tuple}, Tuple{Int64}})
precompile(Tuple{typeof(Base.convert), Type{Integer}, Int64})
precompile(Tuple{typeof(Base.:(<=)), Int64, UInt8})
precompile(Tuple{typeof(Base.:(<=)), UInt8, Int64})
precompile(Tuple{typeof(Base.rem), UInt8, Type{Int64}})
precompile(Tuple{typeof(Base.convert), Type{Signed}, UInt16})
precompile(Tuple{typeof(Base.convert), Type{Signed}, UInt8})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, JulGame.Component.RigidbodyModule.InternalRigidbody, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, JulGame.Component.ColliderModule.InternalCollider, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{Type{UndefKeywordError}, Symbol})
precompile(Tuple{typeof(Base.cconvert), Type{Ptr{Int32}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Ptr{Int32}}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.convert), Type{UInt32}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_EventType})
precompile(Tuple{Type{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_MouseButtonEvent}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_EventType, Vararg{Int64, 9}})
precompile(Tuple{typeof(Base.convert), Type{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_MouseButtonEvent}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_MouseButtonEvent})
precompile(Tuple{typeof(Base.convert), Type{Float64}, Float64})
precompile(Tuple{typeof(Base.literal_pow), typeof(Base.:(^)), Float64, Base.Val{66}})
precompile(Tuple{typeof(Base.literal_pow), typeof(Base.:(^)), Float64, Base.Val{-27}})
precompile(Tuple{typeof(Base.:(/)), Float64, Int64})
precompile(Tuple{typeof(Base.:(*)), Int64, Float64})
precompile(Tuple{typeof(Base.sqrt), Float64})
precompile(Tuple{typeof(Base.:(/)), Base.Irrational{:π}, Int64})
precompile(Tuple{Type{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Rect}, Vararg{Int64, 4}})
precompile(Tuple{typeof(Base.getproperty), Base.Order.By{JulGame.MainLoopModule.var"#9#10", Base.Order.ForwardOrdering}, Symbol})
precompile(Tuple{typeof(Base.getproperty), Base.Order.Lt{Base.Sort.var"#30#31"{Base.Order.By{JulGame.MainLoopModule.var"#9#10", Base.Order.ForwardOrdering}}}, Symbol})
precompile(Tuple{typeof(Core.checked_dims), Int64, Int64})
precompile(Tuple{typeof(Base.:(/)), Int64, Base.Irrational{:π}})
precompile(Tuple{Type{NamedTuple{(:by, :rev), T} where T<:Tuple}, Tuple{typeof(JulGame.Component.Mesh3DModule.avg_z), Bool}})
precompile(Tuple{typeof(Base.getproperty), Base.Order.By{typeof(JulGame.Component.Mesh3DModule.avg_z), Base.Order.ForwardOrdering}, Symbol})
precompile(Tuple{typeof(Base.getproperty), Base.Order.Lt{Base.Sort.var"#30#31"{Base.Order.By{typeof(JulGame.Component.Mesh3DModule.avg_z), Base.Order.ForwardOrdering}}}, Symbol})
precompile(Tuple{typeof(Base.getproperty), Base.Order.By{typeof(JulGame.Component.Mesh3DModule.avg_z), Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}}, Symbol})
precompile(Tuple{typeof(Base.getproperty), Base.Order.Lt{Base.Sort.var"#30#31"{Base.Order.By{typeof(JulGame.Component.Mesh3DModule.avg_z), Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}}}}, Symbol})
precompile(Tuple{Type{Base.Pairs{Symbol, V, I, A} where A where I where V}, NamedTuple{(:by,), Tuple{JulGame.MainLoopModule.var"#6#8"}}, Tuple{Symbol}})
precompile(Tuple{typeof(Base.getproperty), Base.Order.By{JulGame.MainLoopModule.var"#6#8", Base.Order.ForwardOrdering}, Symbol})
precompile(Tuple{typeof(Base.getproperty), Base.Order.Lt{Base.Sort.var"#30#31"{Base.Order.By{JulGame.MainLoopModule.var"#6#8", Base.Order.ForwardOrdering}}}, Symbol})
precompile(Tuple{Type{NamedTuple{(:error,), T} where T<:Tuple}, Tuple{Bool}})
precompile(Tuple{typeof(Base.keys), Base.Dict{String, Any}})
precompile(Tuple{typeof(Base.getproperty), Base.KeySet{String, Base.Dict{String, Any}}, Symbol})
precompile(Tuple{Type{NamedTuple{(:filterlist,), T} where T<:Tuple}, Tuple{String}})
precompile(Tuple{Type{Base.Cstring}, Ptr{Nothing}})
precompile(Tuple{Type{Ptr{UInt8}}, Int64})
precompile(Tuple{typeof(Base.:(|)), CImGui.lib.ImGuiButtonFlags_, CImGui.lib.ImGuiButtonFlags_})
precompile(Tuple{typeof(Base.min), Float32, Float32})
precompile(Tuple{typeof(Base.convert), Type{Int64}, Float32})
precompile(Tuple{typeof(Base.min), Float64, Float64})
precompile(Tuple{Type{Signed}, UInt64})
precompile(Tuple{typeof(Base.getproperty), Base.MappingRF{Base.var"#361#362"{Editor.var"#36#39"}, Base.BottomRF{typeof(Base.add_sum)}}, Symbol})
precompile(Tuple{typeof(Base.Filesystem.joinpath), String})
precompile(Tuple{JulGame.Component.RigidbodyModule.var"#_#1#2", Float64, Bool, Type{JulGame.Component.RigidbodyModule.Rigidbody}})
precompile(Tuple{typeof(Base.getproperty), JulGame.Component.RigidbodyModule.Rigidbody, Symbol})
precompile(Tuple{Type{NamedTuple{(:mass, :useGravity), T} where T<:Tuple}, Tuple{Float64, Bool}})
precompile(Tuple{Type{JulGame.Component.SoundSourceModule.SoundSource}, Int64, Bool, String, Bool, Int64})
precompile(Tuple{typeof(Base.getproperty), JulGame.Component.SoundSourceModule.SoundSource, Symbol})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{String, Int64}, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{String, Int64}, Int64, Int64})
precompile(Tuple{typeof(Base.:(|)), Int64, CImGui.lib.ImGuiColorEditFlags_})
precompile(Tuple{typeof(Base.:(|)), CImGui.lib.ImGuiColorEditFlags_, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Pair{String, Int64}, Int64}, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Pair{String, Int64}, Int64}, Int64, Int64})
precompile(Tuple{typeof(Base.iterate), Pair{String, Int64}})
precompile(Tuple{typeof(Base.iterate), Pair{String, Int64}, Int64})
precompile(Tuple{Type{NamedTuple{(:default,), T} where T<:Tuple}, Tuple{String}})
precompile(Tuple{typeof(Base.:(|)), CImGui.lib.ImGuiColorEditFlags_, CImGui.lib.ImGuiColorEditFlags_})
precompile(Tuple{typeof(Base.:(|)), UInt32, CImGui.lib.ImGuiColorEditFlags_})
precompile(Tuple{typeof(Base.:(+)), Float32, Int64})
precompile(Tuple{Editor.var"##s12#4", Vararg{Any, 5}})
precompile(Tuple{typeof(Base.findfirst), Function, Tuple{Symbol, Symbol, Symbol}})
precompile(Tuple{typeof(Base._findfirst_rec), Editor.var"#5#6"{Symbol}, Int64, Tuple{Symbol, Symbol, Symbol}})
precompile(Tuple{Type{UInt32}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_bool})
precompile(Tuple{typeof(Base.round), Float32})
precompile(Tuple{typeof(Base.print), Base.GenericIOBuffer{GenericMemory{:not_atomic, UInt8, Core.AddrSpace{Core}(0x00)}}, UInt8})
precompile(Tuple{typeof(Base.replace), String, Pair{String, String}})
precompile(Tuple{typeof(Base.parse), Type{Int32}, String})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_CreateTexture), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_PixelFormatEnum, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_TextureAccess, Float32, Float32})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_CreateTexture), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_PixelFormatEnum, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_TextureAccess, Int64, Int64})
precompile(Tuple{Type{JulGame.Math._Vector2{Int32}}, Int64, Int64})
precompile(Tuple{Type{JulGame.Math._Vector3{Float64}}})
precompile(Tuple{Type{JulGame.Math._Vector2{Float64}}, Float64, Float64})
precompile(Tuple{typeof(Base.setproperty!), JulGame.CameraModule.Camera, Symbol, JulGame.Math._Vector2{Float64}})
precompile(Tuple{typeof(Base._array_for), Type{Base.SubString{String}}, Base.HasShape{1}, Tuple{Base.OneTo{Int64}}})
precompile(Tuple{typeof(Base.getproperty), NamedTuple{(:path, :timestamp), Tuple{Base.SubString{String}, Base.SubString{String}}}, Symbol})
precompile(Tuple{typeof(Base.:(!=)), Base.SubString{String}, String})
precompile(Tuple{typeof(Base.Filesystem.isdir), Base.SubString{String}})
precompile(Tuple{typeof(Base.setindex!), Base.RefValue{String}, Base.SubString{String}})
precompile(Tuple{typeof(Base.string), Base.SubString{String}})
precompile(Tuple{Base.Filesystem.var"#_walkdir#35"{Bool, Bool, typeof(throw)}, Base.Channel{Tuple{String, Array{String, 1}, Array{String, 1}}}, String})
precompile(Tuple{typeof(Base.setindex!), GenericMemory{:not_atomic, String, Core.AddrSpace{Core}(0x00)}, String, Int64})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_SetWindowTitle), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Window}, String})
precompile(Tuple{typeof(Base.getproperty), Editor.ImGui_ImplSDL2_Data, Symbol})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_GetWindowSize), Ptr{Any}, Base.RefValue{Int32}, Base.RefValue{Int32}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_GetWindowFlags), Ptr{Any}})
precompile(Tuple{typeof(Base.:(!=)), Ptr{Any}, Ptr{Nothing}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_GetRendererOutputSize), Ptr{Any}, Base.RefValue{Int32}, Base.RefValue{Int32}})
precompile(Tuple{typeof(Base.:(>)), UInt64, Int64})
precompile(Tuple{typeof(Base.setproperty!), Ptr{CImGui.lib.ImGuiIO}, Symbol, Float64})
precompile(Tuple{typeof(Base.unsafe_store!), Ptr{Float32}, Float64})
precompile(Tuple{typeof(Base.setproperty!), Editor.ImGui_ImplSDL2_Data, Symbol, UInt64})
precompile(Tuple{typeof(Base.:(!=)), Int32, Int64})
precompile(Tuple{typeof(Base.:(==)), Ptr{Any}, Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Window}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_GetWindowPosition), Ptr{Any}, Base.RefValue{Int32}, Base.RefValue{Int32}})
precompile(Tuple{typeof(Base.getindex), Array{Ptr{Any}, 1}, Int64})
precompile(Tuple{typeof(Base.:(!=)), Ptr{Any}, Ptr{Any}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_SetCursor), Ptr{Any}})
precompile(Tuple{typeof(Base.setproperty!), Editor.ImGui_ImplSDL2_Data, Symbol, Ptr{Any}})
precompile(Tuple{typeof(Editor.show_main_menu_bar), Base.Dict{String, Function}, Nothing, Array{Base.SubString{String}, 1}})
precompile(Tuple{typeof(CImGui.BeginMenu), String})
precompile(Tuple{typeof(Base.Filesystem.abspath), Base.SubString{String}})
precompile(Tuple{typeof(CImGui.BeginPopupContextItem), String})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_GetWindowTitle), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Window}})
precompile(Tuple{typeof(Base.getproperty), JulGame.CameraModule.Camera, Symbol})
precompile(Tuple{typeof(Base.getproperty), JulGame.Math._Vector2{Int32}, Symbol})
precompile(Tuple{typeof(Base.:(!=)), Int32, Float32})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_CreateTexture), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_PixelFormatEnum, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_TextureAccess, Int32, Int32})
precompile(Tuple{Type{CImGui.lib.ImVec2}, Int32, Int32})
precompile(Tuple{typeof(Editor.show_scene_window), Nothing, Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Texture}, Base.RefValue{CImGui.lib.ImVec2}, Base.RefValue{Float64}, Bool, JulGame.CameraModule.Camera})
precompile(Tuple{typeof(Base.eachindex), Array{Bool, 1}})
precompile(Tuple{typeof(Base.getproperty), JulGame.Math._Vector2{Float64}, Symbol})
precompile(Tuple{Type{Ref{T} where T}, Float32})
precompile(Tuple{typeof(CImGui.InputFloat), String, Base.RefValue{Float32}, Int64})
precompile(Tuple{typeof(Base.getproperty), JulGame.Math._Vector3{Float64}, Symbol})
precompile(Tuple{typeof(Base.getindex), Type{Float32}, Float32, Float32, Float32, Vararg{Float32}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_SetRenderTarget), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Texture}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderClear), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_SetRenderTarget), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.:(>)), Float64, Int64})
precompile(Tuple{typeof(Base.getproperty), Ptr{CImGui.lib.ImGuiIO}, Symbol})
precompile(Tuple{typeof(Base.getproperty), Ptr{CImGui.lib.ImVec2}, Symbol})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderSetScale), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Float32, Float32})
precompile(Tuple{typeof(Base.getindex), Array{Float32, 1}, Int64})
precompile(Tuple{typeof(Base.:(*)), Float32, Int64})
precompile(Tuple{Type{UInt8}, Float32})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_SetRenderDrawColor), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Vararg{UInt8, 4}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderGetScale), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Base.RefValue{Float32}, Base.RefValue{Float32}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderIsClipEnabled), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderGetViewport), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Base.RefValue{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Rect}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderGetClipRect), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Base.RefValue{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Rect}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderSetViewport), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Ptr{Nothing}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderSetClipRect), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Ptr{Nothing}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderSetClipRect), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Base.RefValue{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Rect}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderGeometryRaw), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Texture}, Ptr{Float32}, Int32, Ptr{Int64}, Int32, Ptr{Float32}, Int32, UInt32, Ptr{UInt16}, Int64, Int64})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderSetViewport), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Base.RefValue{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Rect}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderPresent), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}})
precompile(Tuple{Type{Pair{A, B} where B where A}, String, FileWatching.FileEvent})
precompile(Tuple{typeof(Base.:(==)), Base.SubString{String}, String})
precompile(Tuple{typeof(Base.getproperty), Pair{String, FileWatching.FileEvent}, Symbol})
precompile(Tuple{typeof(Base.setproperty!), Editor.ImGui_ImplSDL2_Data, Symbol, UInt32})
precompile(Tuple{typeof(Base.setproperty!), Editor.ImGui_ImplSDL2_Data, Symbol, Int64})
precompile(Tuple{typeof(Base.:(|)), Int32, Int64})
precompile(Tuple{typeof(Base.:(&)), Int32, Int64})
precompile(Tuple{typeof(Editor.load_scene), String, Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}})
precompile(Tuple{typeof(Base.println), Base.TTY, String, Vararg{String}})
precompile(Tuple{typeof(Base.active_project), Bool})
precompile(Tuple{typeof(Base.setproperty!), JulGame.InputModule.Input, Symbol, JulGame.Math._Vector2{Int32}})
precompile(Tuple{Type{JulGame.Math._Vector2{Float64}}, Int64, Int64})
precompile(Tuple{typeof(Base.setproperty!), JulGame.InputModule.Input, Symbol, JulGame.Math._Vector2{Float64}})
precompile(Tuple{typeof(Base.setproperty!), JulGame.WindowManagerModule.WindowManager, Symbol, JulGame.Math._Vector2{Int32}})
precompile(Tuple{typeof(Base.setproperty!), JulGame.WindowManagerModule.WindowManager, Symbol, JulGame.Math._Vector2{Float64}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_initFramerate), Base.RefValue{JulGame.SimpleDirectMediaLayer.LibSDL2.FPSmanager}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_setFramerate), Base.RefValue{JulGame.SimpleDirectMediaLayer.LibSDL2.FPSmanager}, UInt32})
precompile(Tuple{Base.var"##open#463", Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(Base.open), JulGame.SceneManagement.SceneBuilderModule.var"#12#13"{Base.Dict{String, String}}, String, Vararg{String}})
precompile(Tuple{JulGame.Logging.ErrorLoggingModule.var"#1#2"{JulGame.Logging.ErrorLoggingModule.ErrorLogger}})
precompile(Tuple{typeof(Base.wait), Base.GenericCondition{Base.AlwaysLockedST}})
precompile(Tuple{typeof(Base.setproperty!), JulGame.MainLoopModule.MainLoop, Symbol, Bool})
precompile(Tuple{typeof(Base.setproperty!), JulGame.MainLoopModule.MainLoop, Symbol, Float64})
precompile(Tuple{typeof(Base.setproperty!), JulGame.MainLoopModule.MainLoop, Symbol, JulGame.SceneManagement.SceneBuilderModule.Scene})
precompile(Tuple{typeof(Base.getproperty), JulGame.MainLoopModule.MainLoop, Symbol})
precompile(Tuple{typeof(Base.split), String, String})
precompile(Tuple{typeof(Base.getindex), Array{Base.SubString{String}, 1}, Int64})
precompile(Tuple{typeof(Base.setproperty!), JulGame.SceneModule.Scene, Symbol, Base.SubString{String}})
precompile(Tuple{typeof(Base.:(==)), JulGame.Math._Vector2{Int32}, JulGame.Math._Vector2{Int32}})
precompile(Tuple{typeof(Base.getproperty), JulGame.SceneBuilderModule.JSON3.Object{Base.CodeUnits{UInt8, String}, Array{UInt64, 1}}, Symbol})
precompile(Tuple{typeof(Base.iterate), JulGame.SceneBuilderModule.JSON3.Array{JulGame.SceneBuilderModule.JSON3.Object{S, TT} where TT<:AbstractArray{UInt64, 1} where S<:AbstractArray{UInt8, 1}, Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}})
precompile(Tuple{typeof(Base.getproperty), JulGame.SceneBuilderModule.JSON3.Object{Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}, Symbol})
precompile(Tuple{typeof(JulGame.SceneManagement.SceneReaderModule.deserialize_component), JulGame.SceneBuilderModule.JSON3.Object{Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}})
precompile(Tuple{Type{JulGame.Math._Vector4{Int32}}, Vararg{Int64, 4}})
precompile(Tuple{Type{JulGame.Component.SpriteModule.Sprite}, NTuple{4, Int64}, JulGame.Math._Vector4{Int32}, Bool, String, Bool, Int64, JulGame.Math._Vector2{Float64}, JulGame.Math._Vector2{Float64}, Float64, Int64, JulGame.Math._Vector2{Float64}})
precompile(Tuple{typeof(Base.iterate), JulGame.SceneBuilderModule.JSON3.Array{JulGame.SceneBuilderModule.JSON3.Object{S, TT} where TT<:AbstractArray{UInt64, 1} where S<:AbstractArray{UInt8, 1}, Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}, Tuple{Int64, Int64}})
precompile(Tuple{Type{JulGame.Component.TransformModule.Transform}, JulGame.Math._Vector2{Float64}, JulGame.Math._Vector2{Float64}})
precompile(Tuple{Type{JulGame.Math._Vector3{Float64}}, Float64, Float64, Float64})
precompile(Tuple{typeof(Base.haskey), JulGame.SceneBuilderModule.JSON3.Object{Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}, String})
precompile(Tuple{typeof(Base.get), JulGame.SceneBuilderModule.JSON3.Object{Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}, String, String})
precompile(Tuple{Type{JulGame.Component.TransformModule.Transform}, JulGame.Math._Vector3{Float64}})
precompile(Tuple{Type{JulGame.Component.TransformModule.Transform}, JulGame.Math._Vector3{Float64}, JulGame.Math._Vector3{Float64}})
precompile(Tuple{typeof(Base.get), JulGame.SceneBuilderModule.JSON3.Object{Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}, String, Bool})
precompile(Tuple{typeof(Base.setproperty!), JulGame.EntityModule.Entity, Symbol, Bool})
precompile(Tuple{typeof(Base.get), JulGame.SceneBuilderModule.JSON3.Object{Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}, String, Array{Any, 1}})
precompile(Tuple{typeof(Base.setproperty!), JulGame.EntityModule.Entity, Symbol, JulGame.SceneBuilderModule.JSON3.Array{JulGame.SceneBuilderModule.JSON3.Object{S, TT} where TT<:AbstractArray{UInt64, 1} where S<:AbstractArray{UInt8, 1}, Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}})
precompile(Tuple{typeof(Base.convert), Type{Array{Any, 1}}, JulGame.SceneBuilderModule.JSON3.Array{JulGame.SceneBuilderModule.JSON3.Object{S, TT} where TT<:AbstractArray{UInt64, 1} where S<:AbstractArray{UInt8, 1}, Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}})
precompile(Tuple{Type{JulGame.Math._Vector2{Int32}}, Int32, Int32})
precompile(Tuple{typeof(Base.setproperty!), JulGame.Component.SpriteModule.InternalSprite, Symbol, JulGame.Math._Vector2{Int32}})
precompile(Tuple{typeof(Base.setproperty!), JulGame.EntityModule.Entity, Symbol, JulGame.SceneBuilderModule.JSON3.Array{Union{}, Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}})
precompile(Tuple{typeof(Base.convert), Type{Array{Any, 1}}, JulGame.SceneBuilderModule.JSON3.Array{Union{}, Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}})
precompile(Tuple{typeof(Base.getproperty), JulGame.EntityModule.Entity, Symbol})
precompile(Tuple{typeof(Base.string), JulGame.SceneBuilderModule.JSON3.Object{Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}})
precompile(Tuple{typeof(Core.Compiler._typename), Union})
precompile(Tuple{typeof(JulGame.SceneManagement.SceneReaderModule.deserialize_ui_elements), JulGame.SceneBuilderModule.JSON3.Array{JulGame.SceneBuilderModule.JSON3.Object{S, TT} where TT<:AbstractArray{UInt64, 1} where S<:AbstractArray{UInt8, 1}, Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}})
precompile(Tuple{typeof(Base.get), JulGame.SceneBuilderModule.JSON3.Object{Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}, String, JulGame.Math._Vector2{Int32}})
precompile(Tuple{typeof(Core.kwcall), NamedTuple{(:id, :name, :anchor, :anchorOffset, :isWorldEntity, :layer, :position, :isActive, :persistentBetweenScenes, :color, :fontPath, :fontSize, :maxLineWidth, :wrapWords), Tuple{String, String, Symbol, JulGame.Math._Vector2{Int32}, Bool, Int64, JulGame.Math._Vector2{Int32}, Bool, Bool, NTuple{4, Int64}, String, Int64, Int64, Bool}}, Type{JulGame.UI.TextBoxModule.TextBox}, String})
precompile(Tuple{typeof(Base.haskey), Base.Dict{JulGame.UI.UIElement, JulGame.UI.UIElementInstance}, JulGame.UI.TextBoxModule.TextBox})
precompile(Tuple{typeof(Base.setindex!), Base.Dict{JulGame.UI.UIElement, JulGame.UI.UIElementInstance}, JulGame.UI.UIElementInstance, JulGame.UI.TextBoxModule.TextBox})
precompile(Tuple{typeof(Base.getindex), Base.Dict{JulGame.UI.UIElement, JulGame.UI.UIElementInstance}, JulGame.UI.TextBoxModule.TextBox})
precompile(Tuple{typeof(Base.setproperty!), JulGame.Enum{Any}, Symbol, Symbol})
precompile(Tuple{typeof(Base.:(!=)), Ptr{Nothing}, Ptr{Nothing}})
precompile(Tuple{typeof(Base.pointer), Array{UInt8, 1}})
precompile(Tuple{typeof(Base.length), Array{UInt8, 1}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RWFromConstMem), Ptr{UInt8}, Int64})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.TTF_OpenFontRW), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RWops}, Int64, Int32})
precompile(Tuple{typeof(Base.:(==)), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2._TTF_Font}, Ptr{Nothing}})
precompile(Tuple{Type{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Color}, Vararg{Int32, 4}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.TTF_RenderUTF8_Blended), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2._TTF_Font}, String, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Color})
precompile(Tuple{typeof(Base.:(==)), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Surface}, Ptr{Nothing}})
precompile(Tuple{typeof(Core.kwcall), NamedTuple{(:own,), Tuple{Bool}}, typeof(Base.unsafe_wrap), Type{Array{T, N} where N where T}, Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Surface}, Int64})
precompile(Tuple{typeof(Base.getindex), Array{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Surface, 1}, Int64})
precompile(Tuple{typeof(Base.getproperty), JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Surface, Symbol})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_CreateTextureFromSurface), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Surface}})
precompile(Tuple{typeof(Base.:(==)), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Texture}, Ptr{Nothing}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_SetTextureScaleMode), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Texture}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_ScaleMode})
precompile(Tuple{typeof(Base.getproperty), JulGame.SceneModule.Scene, Symbol})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.TTF_OpenFont), String, Int32})
precompile(Tuple{typeof(Base.haskey), JulGame.SceneBuilderModule.JSON3.Object{Base.CodeUnits{UInt8, String}, Array{UInt64, 1}}, String})
precompile(Tuple{Type{JulGame.Math._Vector3{Float64}}, Int64, Int64, Float64})
precompile(Tuple{typeof(Base.setproperty!), JulGame.SceneModule.Scene, Symbol, Array{Any, 1}})
precompile(Tuple{typeof(Base.setproperty!), JulGame.SceneModule.Scene, Symbol, JulGame.CameraModule.Camera})
precompile(Tuple{typeof(Base.setproperty!), JulGame.SceneModule.Scene, Symbol, Array{JulGame.Component.RigidbodyModule.InternalRigidbody, 1}})
precompile(Tuple{typeof(Base.setproperty!), JulGame.SceneModule.Scene, Symbol, Array{JulGame.Component.ColliderModule.InternalCollider, 1}})
precompile(Tuple{typeof(Base.in), String, Base.Set{String}})
precompile(Tuple{typeof(Base.join), NTuple{5, Symbol}, String})
precompile(Tuple{typeof(Base.join), Base.GenericIOBuffer{GenericMemory{:not_atomic, UInt8, Core.AddrSpace{Core}(0x00)}}, NTuple{5, Symbol}, String})
precompile(Tuple{typeof(Base.vect), Pair{String, String}, Vararg{Pair{String, String}}})
precompile(Tuple{typeof(Base.JuliaSyntax.core_parser_hook), Base.SubString{String}, String, Int64, Int64, Symbol})
precompile(Tuple{Type{Base.Dict{Symbol, Int64}}, NTuple{7, Pair{Symbol, Int64}}})
precompile(Tuple{typeof(Base.push!), Base.Set{String}, String})
precompile(Tuple{typeof(Core.memoryref), GenericMemory{:not_atomic, JulGame.SceneBuilderModule.JSON3.Object{S, TT} where TT<:AbstractArray{UInt64, 1} where S<:AbstractArray{UInt8, 1}, Core.AddrSpace{Core}(0x00)}})
precompile(Tuple{typeof(Base.:(-)), UInt64})
precompile(Tuple{typeof(Base.mod), UInt64, UInt64})
precompile(Tuple{Type{NamedTuple{(:name, :level, :maxHealth, :currentHealth, :attack, :defense), T} where T<:Tuple}, Tuple{String, Vararg{Int64, 5}}})
precompile(Tuple{Type{NamedTuple{(:type, :name), T} where T<:Tuple}, Tuple{String, String}})
precompile(Tuple{typeof(Base.get), JulGame.SceneBuilderModule.JSON3.Object{Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}, String, Base.Dict{Any, Any}})
precompile(Tuple{typeof(Base.iterate), JulGame.SceneBuilderModule.JSON3.Object{Base.CodeUnits{UInt8, String}, Base.SubArray{UInt64, 1, Array{UInt64, 1}, Tuple{Base.UnitRange{Int64}}, true}}})
precompile(Tuple{typeof(Base.setproperty!), JulGame.MainLoopModule.MainLoop, Symbol, String})
precompile(Tuple{typeof(JulGame.MainLoopModule.prepare_window_scripts_and_start_loop), JulGame.Math._Vector2{Int32}})
precompile(Tuple{typeof(Base.:(!=)), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2._TTF_Font}, Ptr{Nothing}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.TTF_CloseFont), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2._TTF_Font}})
precompile(Tuple{typeof(Base.:(!=)), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Surface}, Ptr{Nothing}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_FreeSurface), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Surface}})
precompile(Tuple{typeof(Base.:(!=)), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Texture}, Ptr{Nothing}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_DestroyTexture), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Texture}})
precompile(Tuple{typeof(Base.getproperty), JulGame.Enum{Any}, Symbol})
precompile(Tuple{typeof(Base.getproperty), JulGame.Component.SpriteModule.InternalSprite, Symbol})
precompile(Tuple{typeof(Base.string), Int64})
precompile(Tuple{typeof(Base.haskey), Base.Dict{String, Array{T, N} where N where T}, String})
precompile(Tuple{typeof(Base.vect), JulGame.Component.SpriteModule.InternalSprite})
precompile(Tuple{typeof(Base.setindex!), Base.Dict{String, Array{T, N} where N where T}, Array{JulGame.Component.SpriteModule.InternalSprite, 1}, String})
precompile(Tuple{typeof(Base.sort!), Array{Any, 1}})
precompile(Tuple{typeof(Editor.show_scene_window), JulGame.MainLoopModule.MainLoop, Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Texture}, Base.RefValue{CImGui.lib.ImVec2}, Base.RefValue{Float64}, Bool, JulGame.CameraModule.Camera})
precompile(Tuple{Type{JulGame.Math._Vector2{Int32}}, Float32, Float32})
precompile(Tuple{typeof(Base.getproperty), JulGame.Component.TransformModule.Transform, Symbol})
precompile(Tuple{typeof(Base.:(/)), Int32, Float64})
precompile(Tuple{typeof(Base.:(>)), Float64, Float64})
precompile(Tuple{Type{JulGame.Math._Vector2{Int32}}, Float64, Float64})
precompile(Tuple{typeof(Base.:(==)), JulGame.Math._Vector4{Int32}, JulGame.Math._Vector4{Int32}})
precompile(Tuple{typeof(Base.:(-)), Float64, Int32})
precompile(Tuple{typeof(Base.:(*)), Int32, Float64, Float64})
precompile(Tuple{typeof(Base.round), Float64})
precompile(Tuple{typeof(JulGame.Math.TypeConversions.safe_int32_convert), Float64})
precompile(Tuple{typeof(Base.round), Int32})
precompile(Tuple{typeof(JulGame.Math.TypeConversions.safe_int32_convert), Int32})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderCopyEx), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Texture}, Ptr{Nothing}, Base.RefValue{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Rect}, Float64, Base.RefValue{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Point}, JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RendererFlip})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_SetRenderDrawColor), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Vararg{Int64, 4}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderFillRectF), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Base.RefValue{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_FRect}})
precompile(Tuple{typeof(Base.:(/)), JulGame.Math._Vector2{Float64}, Float64})
precompile(Tuple{typeof(Base.Order.lt), Base.Order.ForwardOrdering, Int64, Int64})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_RenderCopyF), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}, Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Texture}, Ptr{Nothing}, Base.RefValue{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_FRect}})
precompile(Tuple{typeof(Base.:(+)), Int32, Float64})
precompile(Tuple{Type{JulGame.Math._Vector2{Float64}}, Int32, Int32})
precompile(Tuple{typeof(Base.notify), Base.GenericCondition{Base.AlwaysLockedST}})
precompile(Tuple{typeof(Base.:(!=)), JulGame.CameraModule.Camera, JulGame.CameraModule.Camera})
precompile(Tuple{typeof(Base.getproperty), JulGame.InputModule.Input, Symbol})
precompile(Tuple{typeof(Base.setproperty!), JulGame.InputModule.Input, Symbol, Function})
precompile(Tuple{typeof(Base.vect), JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Scancode})
precompile(Tuple{typeof(JulGame.InputModule.check_scan_code), JulGame.InputModule.Input, Array{UInt8, 1}, Int64, Array{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Scancode, 1}})
precompile(Tuple{typeof(Base.in), Base.SubString{String}, Array{String, 1}})
precompile(Tuple{typeof(Editor.show_main_menu_bar), Base.Dict{String, Function}, JulGame.MainLoopModule.MainLoop, Array{Base.SubString{String}, 1}})
precompile(Tuple{typeof(Base.in), UInt8, Array{Any, 1}})
precompile(Tuple{typeof(Base.findnext), JulGame.InputModule.var"#3#4"{UInt8}, Array{Any, 1}, Int64})
precompile(Tuple{JulGame.InputModule.var"#3#4"{UInt8}, UInt8})
precompile(Tuple{typeof(Base.deleteat!), Array{Any, 1}, Int64})
precompile(Tuple{typeof(Base.eachindex), Array{Any, 1}})
precompile(Tuple{typeof(Editor.handle_childless_entity_selection), JulGame.EntityModule.Entity, Array{Any, 1}, Int64, JulGame.MainLoopModule.MainLoop, Editor.ConfirmationModal})
precompile(Tuple{typeof(Editor.handle_drag_and_drop), Array{Any, 1}, Int64, JulGame.MainLoopModule.MainLoop, Array{Any, 1}})
precompile(Tuple{typeof(Editor.show_field_editor), JulGame.EntityModule.Entity, Symbol, Base.RefValue{Base.Dict{Any, Any}}, Base.RefValue{Base.Dict{Any, Any}}, Base.RefValue{String}})
precompile(Tuple{typeof(Base.count), Array{Bool, 1}})
precompile(Tuple{typeof(Base.length), Array{Bool, 1}})
precompile(Tuple{typeof(Base.fill), Bool, Int64})
precompile(Tuple{typeof(CImGui.PushID), Int64})
precompile(Tuple{typeof(Base.string), Int64, String, Vararg{Any}})
precompile(Tuple{typeof(Base.getindex), Array{Bool, 1}, Int64})
precompile(Tuple{typeof(Base.fill!), Array{Bool, 1}, Bool})
precompile(Tuple{typeof(Base.xor), Bool, Int64})
precompile(Tuple{typeof(Base.setindex!), Array{Bool, 1}, Int64, Int64})
precompile(Tuple{typeof(Editor.show_ui_element_context_menu), JulGame.MainLoopModule.MainLoop, Int64, Editor.ConfirmationModal, Array{Bool, 1}})
precompile(Tuple{typeof(Editor.show_textbox_fields), JulGame.UI.TextBoxModule.TextBox})
precompile(Tuple{typeof(Editor.show_textbox_fields), JulGame.UI.TextBoxModule.TextBox, Symbol})
precompile(Tuple{typeof(Base.strip), String})
precompile(Tuple{typeof(Base.Filesystem.joinpath), Base.SubString{String}})
precompile(Tuple{typeof(Base.getindex), Base.Dict{String, Array{String, 1}}, String})
precompile(Tuple{Type{Ref{T} where T}, Int32})
precompile(Tuple{typeof(CImGui.InputInt), String, Base.RefValue{Int32}, Int64})
precompile(Tuple{typeof(CImGui.InputText), String, String, Int64})
precompile(Tuple{typeof(Base.eachindex), String})
precompile(Tuple{typeof(Base.iterate), Base.EachStringIndex{String}})
precompile(Tuple{typeof(Base.getindex), String, Int64})
precompile(Tuple{Type{Int32}, Char})
precompile(Tuple{typeof(Base.iterate), Base.EachStringIndex{String}, Int64})
precompile(Tuple{Type{Base.SubString{T} where T<:AbstractString}, String, Int64, Int64})
precompile(Tuple{typeof(CImGui.BeginCombo), String, String})
precompile(Tuple{typeof(Base.:(!=)), Int32, Int32})
precompile(Tuple{typeof(CImGui.Checkbox), String, Base.RefValue{Bool}})
precompile(Tuple{typeof(Base.getindex), Type{Float32}, Float64, Float64, Float64, Vararg{Float64}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_DestroyRenderer), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Renderer}})
precompile(Tuple{typeof(JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_DestroyWindow), Ptr{JulGame.SimpleDirectMediaLayer.LibSDL2.SDL_Window}})
precompile(Tuple{typeof(FileWatching.uvfinalize), FileWatching.FolderMonitor})
println("precompile done")