function add_animator end
function add_circle_collider end
function add_click_event end
function add_collider end
function add_collision_event end
function add_rigidbody end
function add_script end
function add_shape end
function add_sound_source end
function add_sprite end
function append_array end
function apply_forces end
function center_text end
function change_scene end
function check_collisions end
function create_entity end
function create_sound_source end
function destroy end
function destroy_entity end
function destroy_ui_element end
function draw end
function flip end
function generate_uuid end
function get_offset end
function get_position end
function get_rotation end
function get_scale end
function get_size end
function get_tag end
function get_type end
function get_velocity end
function handle_event end
function initialize end
function load_button_sprite_editor end
function load_font end
function load_image end
function load_sound end
function on_shutdown end
function play_animation_once end
function render end
function rerender_text end
function set_color end
function set_offset end
function set_position end
function set_rotation end
function set_scale end
function set_size end
function stop_music end
function toggle_sound end
function unload_sound end
function update end
function update_array_value end
function update_font_size end
