#!/usr/bin/env julia
# Julia → TypeScript stub emitter (extend later).
#
#   julia convert.jl
#
# Output path rule: <REPO_ROOT>/_generated/<mirror-of-relative-path>.ts

const REPO_ROOT = normpath(joinpath(@__DIR__, ".."))

default_out_dir() = joinpath(REPO_ROOT, "ts", "_generated")

"""
    ts_output_path(jl_path; repo_root, generated_dir)

Build the `.ts` path as: `joinpath(repo_root, generated_dir, <same relative dirs as jl_path>, <stem>.ts)`.

Example: `repo/src/engine/Foo.jl` → `repo/_generated/src/engine/Foo.ts`

You cannot “edit” a `joinpath` result in place — strings are immutable. Split with `splitdir` / `relpath`, then `joinpath` again.
"""
function ts_output_path(
    jl_path::AbstractString;
    repo_root::AbstractString = REPO_ROOT,
    generated_dir::AbstractString = "_generated",
)::String
    abs_jl = abspath(jl_path)
    abs_root = abspath(repo_root)
    rel = try
        relpath(abs_jl, abs_root)
    catch
        splitdir(abs_jl)[2]  # basename-only fallback
    end
    rel_dir, rel_file = splitdir(rel)
    stem = splitext(rel_file)[1]
    isempty(rel_dir) && return joinpath(abs_root, "ts", generated_dir, stem * ".ts")
    joinpath(abs_root, "ts", generated_dir, rel_dir, stem * ".ts")
end

function emit_stub(path_ts::AbstractString, path_jl::AbstractString)
    mkpath(dirname(path_ts))
    rel = try
        relpath(path_jl, REPO_ROOT)
    catch
        path_jl
    end
    open(path_ts, "w") do io
        println(io, "// Generated by tools/convert.jl from ", rel)
        println(io, "// Stub: transpiler not implemented for this file.")
        println(io, "export {}")
    end
    path_ts
end

function transpile_file(path_jl::AbstractString)
    path_ts = ts_output_path(path_jl)
    emit_stub(path_ts, path_jl)
    parse_file(path_jl, path_ts)
end

function parse_file(path_jl::AbstractString, path_ts::AbstractString)
    mkpath(dirname(path_ts))
    data = read(path_jl, String)
    data = replace_module(data)
    data = replace_end(data)
    data = replace_exports(data)
    data = replace_comments(data)
    data = replace_docstrings(data)
    data = replace_imports_usings(data)
    data = replace_mutable_structs(data)
    data = replace_structs(data)
    data = replace_types(data)
    data = replace_constructor(data)
    data = replace_function_declaration_dots(data)
    data = replace_component_qualified_calls(data)
    data = replace_function_definitions(data)
    data = replace_if_statements(data)
    data = replace_first_assignments_with_let(data)
    data = replace_julia_ts_literals(data)
    data = custom_function_removal(data)
    open(path_ts, "w") do io
        print(io, data)
    end
    path_ts
end

function replace_module(data::AbstractString)
    # replace the line with module with empty string
    data = replace(data, r"module .*" => "")
    # `findlast("end", s)` returns a `UnitRange` of indices, not one integer
    r = findlast("end", data)
    r === nothing && return data
    head = data[1:prevind(data, first(r))]
    return head * ""
end

function replace_end(data::AbstractString)
    # Julia block closer only: plain `r"end"` would mangle identifiers like `append_*`.
    data = replace(data, r"\bend\b" => "}")
    return data
end

function replace_exports(data::AbstractString)
    # replace the line with export with empty string
    data = replace(data, r"export .*" => "")
    return data
end

function replace_comments(data::AbstractString)
    # replace the line with # with empty string
    data = replace(data, r"#" => "//")
    return data
end

# Julia `""" ... """` docstrings → TS block comments. Run after `#` → `//` inside the doc body.
# Break `*/` in the body so the comment does not end early.
function replace_docstrings(data::AbstractString)::String
    s = String(data)
    delim = "\"\"\""
    io = IOBuffer()
    idx = firstindex(s)
    n = lastindex(s)
    while idx <= n
        rg_open = findnext(delim, s, idx)
        if rg_open === nothing
            write(io, SubString(s, idx))
            break
        end
        lo = first(rg_open)
        lo > idx && write(io, SubString(s, idx, prevind(s, lo)))
        inner_start = nextind(s, last(rg_open))
        rg_close = findnext(delim, s, inner_start)
        if rg_close === nothing
            write(io, SubString(s, idx))
            break
        end
        inner_end = prevind(s, first(rg_close))
        body = inner_start <= inner_end ? s[inner_start:inner_end] : ""
        safe = replace(String(body), "*/" => "* /")
        write(io, "/*", safe, "*/")
        idx = nextind(s, last(rg_close))
    end
    return String(take!(io))
end

function replace_julia_ts_literals(data::AbstractString)
    data = replace(data, r"\bC_NULL\b" => "null")
    # `@warn "msg"` — string literal only (no interpolated/extra kwargs on this pass).
    data = replace(data, r"@warn\s+\"([^\"]*)\"" => s"console.warn(\"\1\")")
    return data
end

function replace_imports_usings(data::AbstractString)
    # Comment-out `using` lines; `\1` is the captured match (SubstitutionString).
    data = replace(data, r"(using .*)" => s"// \1")
    data = replace(data, r"(import .*)" => s"// \1")
    return data
end

function replace_mutable_structs(data::AbstractString)
    # `mutable struct Name` → `class Name {` (must capture `\1` in the regex)
    data = replace(data, r"mutable struct\s+(\w+)" => s"class \1 {")
    return data
end

function replace_structs(data::AbstractString)
    # replace the line with struct with empty string
    data = replace(data, r"struct\s+(\w+)" => s"class \1 {")
    return data
end

# Split by commas at top level, ignoring commas inside `{...}`.
function split_top_level_commas(s::AbstractString)::Vector{String}
    out = String[]
    part = IOBuffer()
    depth = 0
    for c in String(s)
        if c == '{'
            depth += 1
            write(part, c)
        elseif c == '}'
            depth -= 1
            write(part, c)
        elseif c == ',' && depth == 0
            push!(out, strip(String(take!(part))))
        else
            write(part, c)
        end
    end
    push!(out, strip(String(take!(part))))
    return out
end

function scalar_type_to_ts(t::AbstractString, scalar_map::Dict{String,String})::String
    t = String(strip(t))
    t == "Ptr{Nothing}" && return "null"
    if startswith(t, "Vector{") && endswith(t, "}")
        inner = t[nextind(t, firstindex(t), 7):prevind(t, lastindex(t))]
        return vector_inner_to_ts(inner, scalar_map)
    end
    if haskey(scalar_map, t)
        return scalar_map[t]
    end
    if occursin('.', t)
        leaf = String(split(t, '.')[end])
        return string(get(scalar_map, leaf, leaf))
    end
    return string(get(scalar_map, t, t))
end

# `::Union{A, B, Ptr{Nothing}}` → `: A | B | null` (brace-balanced).
function replace_union_annotations(data::AbstractString, scalar_map::Dict{String,String})::String
    s = String(data)
    needle = "::Union{"
    io = IOBuffer()
    idx = firstindex(s)
    n = lastindex(s)
    while idx <= n
        rg = findnext(needle, s, idx)
        if rg === nothing
            write(io, SubString(s, idx))
            break
        end
        lo = first(rg)
        brace_open = last(rg)
        lo > idx && write(io, SubString(s, idx, prevind(s, lo)))
        depth = 1
        p = nextind(s, brace_open)
        while p <= n && depth > 0
            c = s[p]
            if c == '{'
                depth += 1
            elseif c == '}'
                depth -= 1
            end
            p = nextind(s, p)
        end
        union_inner = s[nextind(s, brace_open):prevind(s, prevind(s, p))]
        members = split_top_level_commas(union_inner)
        ts_members = map(m -> scalar_type_to_ts(m, scalar_map), members)
        write(io, ": ", join(ts_members, " | "))
        idx = p
    end
    return String(take!(io))
end

function vector_inner_to_ts(inner::AbstractString, scalar_map::Dict{String,String})::String
    inner = String(strip(inner))
    if haskey(scalar_map, inner)
        return scalar_map[inner] * "[]"
    end
    if occursin('.', inner)
        leaf = String(split(inner, '.')[end])
        return string(get(scalar_map, leaf, leaf)) * "[]"
    end
    return string(get(scalar_map, inner, inner)) * "[]"
end

# `::Vector{Inner}` → `: ts[]` using scalar_map for bare names and the last segment for `Mod.Type`.
# Nested `Vector{Vector{Int}}` is not supported (single `[^}]+` capture).
function replace_vector_annotations(data::AbstractString, scalar_map::Dict{String,String})
    s = String(data)
    pat = r"::Vector\{([^}]+)\}"
    io = IOBuffer()
    idx = firstindex(s)
    n = lastindex(s)
    while idx <= n
        rg = findnext(pat, s, idx)
        if rg === nothing
            write(io, SubString(s, idx))
            break
        end
        f = first(rg)
        f > idx && write(io, SubString(s, idx, prevind(s, f)))
        m = match(pat, s, f)
        m === nothing && break
        inner = m[1]::AbstractString
        write(io, ": ", vector_inner_to_ts(inner, scalar_map))
        idx = nextind(s, last(rg))
    end
    return String(take!(io))
end

function replace_types(data::AbstractString)
    scalar_map = Dict{String,String}(
        "Int32" => "number",
        "UInt64" => "number",
        "UInt32" => "number",
        "UInt16" => "number",
        "UInt8" => "number",
        "Int64" => "number",
        "Int16" => "number",
        "Int8" => "number",
        "Float32" => "number",
        "Float64" => "number",
        "String" => "string",
        "Bool" => "boolean",
        "InternalAnimator" => "InternalAnimator",
        "InternalSprite" => "InternalSprite",
        "InternalShape" => "InternalShape",
        "InternalRigidbody" => "InternalRigidbody",
        "InternalSoundSource" => "InternalSoundSource",
        "InternalSprite" => "InternalSprite",
        "InternalShape" => "InternalShape",
        "InternalRigidbody" => "InternalRigidbody",
        "InternalSoundSource" => "InternalSoundSource",
        "Int" => "number",
        "Animation" => "JulGameAnimation",
        "Any" => "any",
    )
    data = replace_union_annotations(data, scalar_map)
    data = replace_vector_annotations(data, scalar_map)
    # Longer keys first so `::Int` does not chew `::Int32` into `: number` + `32`.
    for k in sort(collect(keys(scalar_map)), by = length, rev = true)
        data = replace(data, "::$k" => ": $(scalar_map[k])")
    end
    return data
end

function replace_constructor(data::AbstractString)
    # Julia inner ctor is `function ClassName(args)` (no `{`). Only the ctor whose name
    # matches a `class Name {` in this file becomes `constructor(args)`.
    seen = Set{String}()
    for m in eachmatch(r"class\s+(\w+)\s*\{", data)
        name = m.captures[1]::AbstractString
        name in seen && continue
        push!(seen, name)
        # `name` comes from `(\w+)` on the class line — no regex metacharacters to escape.
        pat = Regex("function\\s+" * string(name) * "\\s*\\(")
        data = replace(data, pat => "constructor(")
    end
    # TS needs `{` before the body; Julia starts the block on the next line.
    data = replace(data, r"(?m)^(\s*constructor\([^)]*\))\s*$" => s"\1 {")

    data = replace(data, "this = new()" => "")
    data = replace(data, "return this" => "")
    return data
end

# `function A.B.c(` → `function A_B_c(` — TS cannot use `.` in a `function` name.
# Uses `findnext` + `match` (no `replace(str, regex, f)` — that overload is newer Julia).
function replace_function_declaration_dots(data::AbstractString)
    s = String(data)
    pat = r"(?m)^(function\s+)([^\s(]+)(\()"
    io = IOBuffer()
    idx = firstindex(s)
    n = lastindex(s)
    while idx <= n
        rg = findnext(pat, s, idx)
        if rg === nothing
            write(io, SubString(s, idx))
            break
        end
        f = first(rg)
        f > idx && write(io, SubString(s, idx, prevind(s, f)))
        m = match(pat, s, f)
        m === nothing && break
        write(io, string(m[1], replace(m[2], "." => "_"), m[3]))
        idx = nextind(s, last(rg))
    end
    return String(take!(io))
end

# `Component.foo(` → `Component_foo(` so calls match mangled declarations.
function replace_component_qualified_calls(data::AbstractString)
    replace(data, r"\bComponent\.(\w+)\s*\(" => s"Component_\1(")
end

function replace_function_definitions(data::AbstractString)
    # Julia: `function qual_name(args)` then newline — no `{`. TS needs `{` on the same line.
    # Name is `[^\s(]+`; `constructor(...)` is unchanged.
    data = replace(data, r"(?m)^(\s*function\s+[^\s(]+\([^)]*\))\s*$" => s"\1 {")
    return data
end

function replace_if_statements(data::AbstractString)
    # Julia: `if cond` then newline — TS: `if (cond) {`. Single-line condition only; else/elseif later.
    s = String(data)
    lines = split(s, '\n'; keepempty = true)
    done_line = r"^\s*if\s*\([^)]*\)\s*\{\s*$"
    pat = r"^(\s*)if\b\s+(.+)$"
    return join(
        map(lines) do line
            occursin(done_line, line) && return line
            m = match(pat, line)
            m === nothing ? line : string(m[1], "if (", strip(m[2]), ") {")
        end,
        '\n',
    )
end

function replace_first_assignments_with_let(data::AbstractString)::String
    lines = split(String(data), '\n'; keepempty = true)
    seen = Set{String}()
    pat = r"^(\s*)([A-Za-z_]\w*)\s*=\s*(.+)$"
    header_pat = r"^\s*(?:function\s+[^\s(]+|constructor)\s*\(([^)]*)\)"
    out = map(lines) do line
        hm = match(header_pat, line)
        if hm !== nothing
            params = split(String(hm[1]), ',')
            for p in params
                pm = match(r"^\s*([A-Za-z_]\w*)", p)
                pm === nothing && continue
                push!(seen, String(pm[1]))
            end
            return line
        end
        m = match(pat, line)
        m === nothing && return line
        indent = String(m[1])
        name = String(m[2])
        rhs = String(m[3])
        # Skip obvious non-declarations / already-TS declarations.
        startswith(rhs, "=") && return line  # `==`, `===`
        startswith(rhs, ">") && return line  # `=>`
        startswith(rhs, "<") && return line  # `=<` / malformed cases
        startswith(name, "this") && return line
        if name in seen
            return line
        end
        push!(seen, name)
        return string(indent, "let ", name, " = ", rhs)
    end
    return join(out, '\n')
end

function custom_function_removal(data::AbstractString)
    functions_to_remove = [
        "Component_update_array_value",
        "Component_append_array",
        "Component_get_type",
    ]
    s = String(data)
    for func in functions_to_remove
        s = remove_ts_function_block(s, func)
    end
    return s
end

# Strip a whole `function name(...) { ... }` (names are already TS/mangled). `r"...$var"` does not interpolate.
function remove_ts_function_block(s::String, func::AbstractString)::String
    pat = Regex("(?m)^\\s*function\\s+" * func * "\\s*\\([^)]*\\)\\s*\\{")
    while true
        rg = findfirst(pat, s)
        rg === nothing && return s
        lo = first(rg)
        hi = last(rg)  # `{` that opens the body

        depth = 1
        p = nextind(s, hi)
        n = lastindex(s)
        while p <= n && depth > 0
            c = s[p]
            if c == '{'
                depth += 1
            elseif c == '}'
                depth -= 1
            end
            p = nextind(s, p)
        end

        fi = firstindex(s)
        prefix = lo > fi ? s[fi:prevind(s, lo)] : ""
        suffix = p <= n ? s[p:n] : ""
        s = string(prefix, suffix)
    end
end

function main()
    files = [joinpath(REPO_ROOT, "src", "engine", "Component", "Animator.jl")]
    mkpath(default_out_dir())
    for f in files
        isfile(f) || error("not a file: $f")
        println(transpile_file(f))
    end
end

main()
