#!/usr/bin/env julia
# Julia → TypeScript stub emitter (extend later).
#
#   julia convert.jl
#
# Output path rule: <REPO_ROOT>/_generated/<mirror-of-relative-path>.ts

const REPO_ROOT = normpath(joinpath(@__DIR__, ".."))

# Generated TS calls Julia-style `InternalFoo(args)` on classes — emit `new InternalFoo(args)`.
# Start with engine `Internal*` component types; append more names as other modules gain classes.
# Do not turn `string[]`, `number[]`, etc. in type positions into ref-cell reads.
const TS_ARRAY_PRIMITIVE_TYPE_NAMES = Set{String}([
    "string",
    "number",
    "boolean",
    "any",
    "void",
    "unknown",
    "never",
    "object",
    "symbol",
    "bigint",
])

const TS_CLASS_NAMES_NEEDING_NEW = String[
    "InternalAnimator",
    "InternalCircleCollider",
    "InternalCollider",
    "InternalRigidbody",
    "InternalShape",
    "InternalSoundSource",
    "InternalSprite",
    "Transform",
]

default_out_dir() = joinpath(REPO_ROOT, "ts", "_generated")

"""
    ts_output_path(jl_path; repo_root, generated_dir)

Build the `.ts` path as: `joinpath(repo_root, generated_dir, <same relative dirs as jl_path>, <stem>.ts)`.

Example: `repo/src/engine/Foo.jl` → `repo/_generated/src/engine/Foo.ts`

You cannot “edit” a `joinpath` result in place — strings are immutable. Split with `splitdir` / `relpath`, then `joinpath` again.
"""
function ts_output_path(
    jl_path::AbstractString;
    repo_root::AbstractString = REPO_ROOT,
    generated_dir::AbstractString = "_generated",
)::String
    abs_jl = abspath(jl_path)
    abs_root = abspath(repo_root)
    rel = try
        relpath(abs_jl, abs_root)
    catch
        splitdir(abs_jl)[2]  # basename-only fallback
    end
    rel_dir, rel_file = splitdir(rel)
    stem = splitext(rel_file)[1]
    isempty(rel_dir) && return joinpath(abs_root, "ts", generated_dir, stem * ".ts")
    joinpath(abs_root, "ts", generated_dir, rel_dir, stem * ".ts")
end

function emit_stub(path_ts::AbstractString, path_jl::AbstractString)
    mkpath(dirname(path_ts))
    rel = try
        relpath(path_jl, REPO_ROOT)
    catch
        path_jl
    end
    open(path_ts, "w") do io
        println(io, "// Generated by tools/convert.jl from ", rel)
        println(io, "// Stub: transpiler not implemented for this file.")
        println(io, "export {}")
    end
    path_ts
end

function transpile_file(path_jl::AbstractString)
    path_ts = ts_output_path(path_jl)
    emit_stub(path_ts, path_jl)
    parse_file(path_jl, path_ts)
end

function parse_file(path_jl::AbstractString, path_ts::AbstractString)
    mkpath(dirname(path_ts))
    data = read(path_jl, String)
    # Drop UTF-8 BOMs copied from source files so generated TS starts cleanly.
    data = replace(data, "\ufeff" => "")
    data = replace_module(data)
    data = replace_end(data)
    data = replace_exports(data)
    data = replace_comments(data)
    data = replace_docstrings(data)
    data = replace_imports_usings_includes(data)
    data = replace_mutable_structs(data)
    data = replace_structs(data)
    data = replace_types(data)
    data = replace_constructor(data)
    data = replace_function_declaration_dots(data)
    data = replace_component_qualified_calls(data)
    data = replace_function_definitions(data)
    data = replace_if_statements(data)
    data = replace_else_elseif_blocks(data)
    data = replace_for_in_loops(data)
    data = replace_first_assignments_with_let(data)
    data = replace_julia_ts_literals(data)
    data = normalize_julia_ref_for_ts(data)
    data = replace_invokelatest_calls(data)
    data = replace_keyword_style_calls_to_object_args(data)
    data = normalize_julgame_global_access(data)
    data = replace_animation_symbol(data)
    data = custom_function_removal(data)
    data = replace_push_calls(data)
    data = remove_!_from_function_names(data)
    data = replace_setfield_calls(data)
    data = replace_empty_vector_literals(data)
    data = rewrite_rhs_vector_arithmetic(data)
    data = prefix_new_for_listed_class_constructors(data)
    data = prepend_generated_ts_imports(data, path_ts)
    data = replace_entire_line_if_matches(data)
    data = "export {}\n" * data
    open(path_ts, "w") do io
        print(io, data)
    end
    path_ts
end

function _line_is_julia_style_internal_ctor_decl(line::AbstractString)::Bool
    m = match(r"^\s*function\s+(\w+)\s*\(", line)
    m === nothing && return false
    return String(m[1]) in TS_CLASS_NAMES_NEEDING_NEW
end

function prefix_new_for_listed_class_constructors(data::AbstractString)::String
    lines = split(String(data), '\n'; keepempty = true)
    out = map(lines) do line
        _line_is_julia_style_internal_ctor_decl(line) && return line
        sline = String(line)
        for t in TS_CLASS_NAMES_NEEDING_NEW
            pat = Regex("(?<!\\bnew\\s)(?<!\\.)\\b" * t * "\\s*\\(")
            sline = replace(sline, pat => "new $(t)(")
        end
        return sline
    end
    return join(out, '\n')
end

function prepend_generated_ts_imports(data::AbstractString, path_ts::AbstractString)::String
    need_clamp = occursin(r"\bclamp\s*\(", data)
    need_vec = occursin(r"\bvec(Add|Sub|Mul|Div|Neg)\(", data)
    (!need_clamp && !need_vec) && return data
    ts_dir = dirname(abspath(path_ts))
    lines = String[]
    if need_clamp
        h = abspath(joinpath(REPO_ROOT, "ts", "src", "engine", "core", "juliaHelpers.ts"))
        if isfile(h)
            rel = replace(String(relpath(h, ts_dir)), '\\' => '/')
            rel = replace(rel, r"\.ts$" => "")
            push!(lines, string("import { clamp } from \"", rel, "\";"))
        end
    end
    if need_vec
        v = abspath(joinpath(REPO_ROOT, "ts", "src", "engine", "core", "vectorOps.ts"))
        if isfile(v)
            relv = replace(String(relpath(v, ts_dir)), '\\' => '/')
            relv = replace(relv, r"\.ts$" => "")
            push!(lines, string("import { vecAdd, vecSub, vecMul, vecDiv, vecNeg } from \"", relv, "\";"))
        end
    end
    isempty(lines) && return data
    return string(join(lines, "\n"), "\n\n", data)
end

# --- Julia-style vector `+ - * /` on plain `{x,y}` / `{x,y,z}` objects (see `src/Math/Vector2.jl`, `Math.jl`) ---

abstract type _VecAst end

struct _Leaf <: _VecAst
    text::String
end

struct _Neg <: _VecAst
    child::_VecAst
end

struct _Bin <: _VecAst
    op::Char
    left::_VecAst
    right::_VecAst
end

struct _Call <: _VecAst
    name::String
    args::Vector{_VecAst}
end

struct _Idx <: _VecAst
    base::_VecAst
    inner::_VecAst
end

mutable struct _Ps
    s::String
    i::Int
    n::Int
end

function _skip_ws!(ps::_Ps)
    while ps.i <= ps.n
        c = ps.s[ps.i]
        (c == ' ' || c == '\t') || break
        ps.i = nextind(ps.s, ps.i)
    end
end

function _peekc(ps::_Ps)::Union{Nothing, Char}
    _skip_ws!(ps)
    ps.i > ps.n && return nothing
    return ps.s[ps.i]
end

const _VECTOR_RHS_GTA_PLACEHOLDER = "__JulGame_GlobalThisJulGame__"

function _vec_ts_cast_suffix(lhs::AbstractString)::String
    ls = String(strip(lhs))
    # Narrow names so we do not cast e.g. `screenPosition` (Vector2) to Vector3f.
    if ls in ("newPosition", "currentPosition", "targetPos")
        return " as Vector3f"
    end
    if ls in (
        "newVelocity",
        "this.velocity",
        "this.acceleration",
        "velocityMultiplier",
        "newAcceleration",
        "gravityAcceleration",
        "dragAcceleration",
        "dragForce",
        "posA",
        "posB",
    )
        return " as Vector2f"
    end
    return ""
end

function _rhs_hints_vector_math(rhs::AbstractString)::Bool
    occursin(r"[+\-*/]", rhs) || return false
    occursin("velocity", rhs) ||
        occursin("acceleration", rhs) ||
        occursin("transform.position", rhs) ||
        occursin("gravityAcceleration", rhs) ||
        occursin("dragAcceleration", rhs) ||
        occursin("dragForce", rhs) ||
        occursin("velocityMultiplier", rhs) ||
        occursin("newVelocity", rhs) ||
        occursin("newPosition", rhs) ||
        occursin("newAcceleration", rhs) ||
        occursin("currentPosition", rhs) ||
        (occursin(".offset", rhs) && occursin("position", rhs))
    # Do not key off `SCALE_UNITS` alone — scalar chains like `scale.x * size.x * SCALE_UNITS` must stay numeric.
end

function _normalize_ts_casts_for_vec_parse(rhs::AbstractString)::String
    replace(String(rhs), r"\(\s*globalThis\s+as\s+any\s*\)" => _VECTOR_RHS_GTA_PLACEHOLDER)
end

function _restore_ts_casts_after_vec_emit(emitted::AbstractString)::String
    replace(String(emitted), _VECTOR_RHS_GTA_PLACEHOLDER => "(globalThis as any)")
end

function _emit_vec_ast(node::_VecAst)::String
    if node isa _Leaf
        return node.text
    elseif node isa _Neg
        return string("vecNeg(", _emit_vec_ast(node.child), ")")
    elseif node isa _Bin
        fn = node.op == '+' ? "vecAdd" :
             node.op == '-' ? "vecSub" :
             node.op == '*' ? "vecMul" : "vecDiv"
        return string(fn, "(", _emit_vec_ast(node.left), ", ", _emit_vec_ast(node.right), ")")
    elseif node isa _Call
        parts = map(_emit_vec_ast, node.args)
        return string(node.name, "(", join(parts, ", "), ")")
    elseif node isa _Idx
        return string(_emit_vec_ast(node.base), "[", _emit_vec_ast(node.inner), "]")
    else
        return ""
    end
end

function _read_atom_token!(ps::_Ps)::Union{Nothing, String}
    _skip_ws!(ps)
    ps.i > ps.n && return nothing
    i0 = ps.i
    c = ps.s[ps.i]
    if isdigit(c) ||
        (c == '.' && ps.i < ps.n && isdigit(ps.s[nextind(ps.s, ps.i)]))
        while ps.i <= ps.n
            cc = ps.s[ps.i]
            if isdigit(cc) || cc == '.' || cc in ('e', 'E', '+', '-')
                ps.i = nextind(ps.s, ps.i)
            else
                break
            end
        end
        return String(SubString(ps.s, i0, prevind(ps.s, ps.i)))
    end
    if isletter(c) || c == '_' || c == '$'
        while ps.i <= ps.n
            cc = ps.s[ps.i]
            if isletter(cc) || isdigit(cc) || cc in ('_', '$', '.')
                ps.i = nextind(ps.s, ps.i)
            else
                break
            end
        end
        return String(SubString(ps.s, i0, prevind(ps.s, ps.i)))
    end
    return nothing
end

function _parse_postfix!(ps::_Ps)::Union{Nothing, _VecAst}
    c0 = _peekc(ps)
    c0 === nothing && return nothing
    local node::_VecAst
    if c0 == '('
        ps.i = nextind(ps.s, ps.i)
        inner = _parse_addsub!(ps)
        inner === nothing && return nothing
        _skip_ws!(ps)
        (ps.i > ps.n || ps.s[ps.i] != ')') && return nothing
        ps.i = nextind(ps.s, ps.i)
        node = inner
    else
        tok = _read_atom_token!(ps)
        tok === nothing && return nothing
        node = _Leaf(tok)
    end
    while true
        c = _peekc(ps)
        c === nothing && break
        if c == '['
            ps.i = nextind(ps.s, ps.i)
            ix = _parse_addsub!(ps)
            ix === nothing && return nothing
            _skip_ws!(ps)
            (ps.i > ps.n || ps.s[ps.i] != ']') && return nothing
            ps.i = nextind(ps.s, ps.i)
            node = _Idx(node, ix)
        elseif c == '('
            node isa _Leaf || return nothing
            name = node.text
            ps.i = nextind(ps.s, ps.i)
            args = _VecAst[]
            c2 = _peekc(ps)
            if c2 == ')'
                ps.i = nextind(ps.s, ps.i)
                node = _Call(name, args)
                continue
            end
            while true
                arg = _parse_addsub!(ps)
                arg === nothing && return nothing
                push!(args, arg)
                c3 = _peekc(ps)
                c3 === nothing && return nothing
                if c3 == ','
                    ps.i = nextind(ps.s, ps.i)
                    continue
                elseif c3 == ')'
                    ps.i = nextind(ps.s, ps.i)
                    break
                else
                    return nothing
                end
            end
            node = _Call(name, args)
        else
            break
        end
    end
    return node
end

function _parse_unary!(ps::_Ps)::Union{Nothing, _VecAst}
    c = _peekc(ps)
    if c == '-'
        ps.i = nextind(ps.s, ps.i)
        ch = _parse_unary!(ps)
        ch === nothing && return nothing
        return _Neg(ch)
    end
    return _parse_postfix!(ps)
end

function _parse_muldiv!(ps::_Ps)::Union{Nothing, _VecAst}
    left = _parse_unary!(ps)
    left === nothing && return nothing
    while true
        c = _peekc(ps)
        c === nothing && break
        if c == '*' || c == '/'
            ps.i = nextind(ps.s, ps.i)
            right = _parse_unary!(ps)
            right === nothing && return nothing
            left = _Bin(c, left, right)
        else
            break
        end
    end
    return left
end

function _parse_addsub!(ps::_Ps)::Union{Nothing, _VecAst}
    left = _parse_muldiv!(ps)
    left === nothing && return nothing
    while true
        c = _peekc(ps)
        c === nothing && break
        if c == '+' || c == '-'
            ps.i = nextind(ps.s, ps.i)
            right = _parse_muldiv!(ps)
            right === nothing && return nothing
            left = _Bin(c, left, right)
        else
            break
        end
    end
    return left
end

function _try_rewrite_rhs_vector_expr(rhs::AbstractString)::Union{Nothing, String}
    r = String(strip(rhs))
    isempty(r) && return nothing
    occursin('"', r) && return nothing
    occursin('\'', r) && return nothing
    r = _normalize_ts_casts_for_vec_parse(r)
    ps = _Ps(r, firstindex(r), lastindex(r))
    tree = _parse_addsub!(ps)
    tree === nothing && return nothing
    _skip_ws!(ps)
    while ps.i <= ps.n && ps.s[ps.i] == ';'
        ps.i = nextind(ps.s, ps.i)
    end
    _skip_ws!(ps)
    ps.i <= ps.n && return nothing
    return _restore_ts_casts_after_vec_emit(_emit_vec_ast(tree))
end

function _matching_paren_close(s::String, open_at::Int)::Union{Nothing, Int}
    depth = 0
    i = open_at
    n = lastindex(s)
    while i <= n
        c = s[i]
        if c == '"'
            j = i
            i = nextind(s, i)
            while i <= n
                cc = s[i]
                if cc == '\\'
                    i = nextind(s, i, 2)
                    continue
                end
                if cc == '"'
                    break
                end
                i = nextind(s, i)
            end
        elseif c == '('
            depth += 1
        elseif c == ')'
            depth -= 1
            depth == 0 && return i
        end
        i = nextind(s, i)
    end
    return nothing
end

function _try_rewrite_set_velocity_line(line::String)::Union{Nothing, String}
    f = findfirst("set_velocity", line)
    f === nothing && return nothing
    i0 = first(f)
    i = last(f)
    while i <= lastindex(line) && line[i] != '('
        i = nextind(line, i)
    end
    i > lastindex(line) && return nothing
    close_i = _matching_paren_close(line, i)
    close_i === nothing && return nothing
    inner = String(SubString(line, nextind(line, i), prevind(line, close_i)))
    parts = split_top_level_commas_general(inner)
    length(parts) < 2 && return nothing
    arg2 = String(strip(parts[2]))
    !_rhs_hints_vector_math(arg2) && return nothing
        rew = _try_rewrite_rhs_vector_expr(arg2)
        rew === nothing && return nothing
        new_inner = string(strip(parts[1]), ", ", rew, " as Vector2f")
    prefix = String(SubString(line, 1, prevind(line, i)))
    suffix = String(SubString(line, nextind(line, close_i)))
    return string(prefix, "(", new_inner, ")", suffix)
end

function _rewrite_vector_arithmetic_line(line::AbstractString)::String
    s = String(rstrip(line, '\r'))
    if occursin("set_velocity", s)
        rw = _try_rewrite_set_velocity_line(s)
        rw !== nothing && return rw
    end
    m = match(r"^(\s*(?:let\s+)?)([A-Za-z_$][\w$.]*)\s*=\s*(.+)$", s)
    if m !== nothing
        rhs = String(strip(m[3]))
        (startswith(rhs, "{") || startswith(rhs, "[") || startswith(rhs, "`")) && return line
        occursin('"', rhs) && return line
        !_rhs_hints_vector_math(rhs) && return line
        rhs0 = rstrip(rhs, ';')
        rew = _try_rewrite_rhs_vector_expr(rhs0)
        if rew !== nothing
            cast = _vec_ts_cast_suffix(String(m[2]))
            return string(m[1], m[2], " = ", rew, cast)
        end
    end
    m2 = match(r"^(\s*return\s+)(.+)$", s)
    if m2 !== nothing
        rhs = String(strip(m2[2]))
        occursin('"', rhs) && return line
        !_rhs_hints_vector_math(rhs) && return line
        rhs0 = rstrip(rhs, ';')
        rew = _try_rewrite_rhs_vector_expr(rhs0)
        if rew !== nothing
            return string(m2[1], rew, " as Vector2f")
        end
    end
    return line
end

function rewrite_rhs_vector_arithmetic(data::AbstractString)::String
    s = String(data)
    parts = split(s, '\n')
    return join(map(_rewrite_vector_arithmetic_line, parts), '\n')
end

function replace_module(data::AbstractString)
    # replace the line with module with empty string
    data = replace(data, r"module .*" => "")
    # `findlast("end", s)` returns a `UnitRange` of indices, not one integer
    r = findlast("end", data)
    r === nothing && return data
    head = data[1:prevind(data, first(r))]
    return head * ""
end

function replace_end(data::AbstractString)
    # Julia block closer only: plain `r"end"` would mangle identifiers like `append_*`.
    data = replace(data, r"\bend\b" => "}")
    return data
end

function replace_exports(data::AbstractString)
    # replace the line with export with empty string
    data = replace(data, r"export .*" => "")
    return data
end

function replace_comments(data::AbstractString)
    # replace the line with # with empty string
    data = replace(data, r"#" => "//")
    return data
end

# Julia `""" ... """` docstrings → TS block comments. Run after `#` → `//` inside the doc body.
# Break `*/` in the body so the comment does not end early.
function replace_docstrings(data::AbstractString)::String
    s = String(data)
    delim = "\"\"\""
    io = IOBuffer()
    idx = firstindex(s)
    n = lastindex(s)
    while idx <= n
        rg_open = findnext(delim, s, idx)
        if rg_open === nothing
            write(io, SubString(s, idx))
            break
        end
        lo = first(rg_open)
        lo > idx && write(io, SubString(s, idx, prevind(s, lo)))
        inner_start = nextind(s, last(rg_open))
        rg_close = findnext(delim, s, inner_start)
        if rg_close === nothing
            write(io, SubString(s, idx))
            break
        end
        inner_end = prevind(s, first(rg_close))
        body = inner_start <= inner_end ? s[inner_start:inner_end] : ""
        safe = replace(String(body), "*/" => "* /")
        write(io, "/*", safe, "*/")
        idx = nextind(s, last(rg_close))
    end
    return String(take!(io))
end

# `TypeConversions.safe_int32_convert(expr)` / `Math.TypeConversions...` -> `expr` (balanced parens for nested calls).
function strip_safe_int32_convert_calls(data::AbstractString)::String
    s = String(data)
    needles = ("Math.TypeConversions.safe_int32_convert(", "TypeConversions.safe_int32_convert(")
    changed = true
    while changed
        changed = false
        fi = firstindex(s)
        n = lastindex(s)
        for needle in needles
            rg = findnext(needle, s, fi)
            rg === nothing && continue
            lo = first(rg)
            inner_start = nextind(s, last(rg))
            close_idx = _find_outer_push_close(s, inner_start, n)
            close_idx === nothing && continue
            inner = s[inner_start:prevind(s, close_idx)]
            pre = s[fi:prevind(s, lo)]
            post = s[nextind(s, close_idx):n]
            s = string(pre, inner, post)
            changed = true
            break
        end
    end
    return s
end

# `UInt32(expr)` -> `expr` when `expr` is a numeric literal; otherwise `((expr) >>> 0)` (unsigned 32-bit in JS).
function strip_uint32_constructor_calls(data::AbstractString)::String
    s = String(data)
    needle = "UInt32("
    changed = true
    while changed
        changed = false
        fi = firstindex(s)
        n = lastindex(s)
        rg = findnext(needle, s, fi)
        rg === nothing && break
        lo = first(rg)
        inner_start = nextind(s, last(rg))
        close_idx = _find_outer_push_close(s, inner_start, n)
        close_idx === nothing && break
        inner = strip(s[inner_start:prevind(s, close_idx)])
        replacement = if occursin(r"^\d+\s*$", inner)
            inner
        else
            string("((", inner, ") >>> 0)")
        end
        pre = s[fi:prevind(s, lo)]
        post = s[nextind(s, close_idx):n]
        s = string(pre, replacement, post)
        changed = true
    end
    return s
end

# Julia `return (a, b, ...)` tuple → TS `return [a, b, ...]` (comma operator is not tuple semantics).
function replace_return_parenthesized_tuples(data::AbstractString)::String
    s = String(data)
    rx = r"return\s+\("
    i = firstindex(s)
    n = lastindex(s)
    io = IOBuffer()
    while i <= n
        rg = findnext(rx, s, i)
        if rg === nothing
            write(io, SubString(s, i))
            break
        end
        lo = first(rg)
        lo > i && write(io, SubString(s, i, prevind(s, lo)))
        open_at = last(rg)
        inner_start = nextind(s, open_at)
        close_idx = _find_outer_push_close(s, inner_start, n)
        if close_idx === nothing
            write(io, SubString(s, lo))
            break
        end
        inner = s[inner_start:prevind(s, close_idx)]
        parts = split_top_level_commas_general(inner)
        if length(parts) < 2 || any(isempty(strip(p)) for p in parts)
            write(io, SubString(s, lo, close_idx))
        else
            write(io, "return [", join(parts, ", "), "]")
        end
        i = nextind(s, close_idx)
    end
    return String(take!(io))
end

# `Math.Vector2(a, b)` / `Vector2f(...)` — regex-only rewrite misses args that contain `(...)`; use balanced parens + top-level comma split.
function replace_math_vector_constructor_calls(data::AbstractString)::String
    needles_meta = (
        ("JulGame.Math.Vector3f(", 3),
        ("JulGame.Math.Vector2f(", 2),
        ("JulGame.Math.Vector2(", 2),
        ("Math.Vector3f(", 3),
        ("Math.Vector2f(", 2),
        ("Math.Vector2(", 2),
        ("Vector3f(", 3),
        ("Vector2f(", 2),
        ("Vector2(", 2),
    )
    s = String(data)
    io = IOBuffer()
    fi = firstindex(s)
    n = lastindex(s)
    while fi <= n
        best_lo = nothing
        best_hi = nothing
        best_arity = 2
        for (needle, arity) in needles_meta
            rg = findnext(needle, s, fi)
            rg === nothing && continue
            lo = first(rg)
            if best_lo === nothing || lo < best_lo
                best_lo = lo
                best_hi = last(rg)
                best_arity = arity
            end
        end
        if best_lo === nothing
            write(io, SubString(s, fi))
            break
        end
        best_lo > fi && write(io, SubString(s, fi, prevind(s, best_lo)))
        inner_start = nextind(s, best_hi)
        close_idx = _find_outer_push_close(s, inner_start, n)
        if close_idx === nothing
            write(io, SubString(s, best_lo))
            break
        end
        inner = s[inner_start:prevind(s, close_idx)]
        parts = split_top_level_commas_general(inner)
        if length(parts) == best_arity
            if best_arity == 2
                write(io, "{x: ", parts[1], ", y: ", parts[2], "}")
            else
                write(io, "{x: ", parts[1], ", y: ", parts[2], ", z: ", parts[3], "}")
            end
        else
            write(io, SubString(s, best_lo, close_idx))
        end
        fi = nextind(s, close_idx)
    end
    return String(take!(io))
end

function replace_julia_ts_literals(data::AbstractString)
    data = replace(data, r"\bC_NULL\b" => "null")
    data = replace(data, r"\bnothing\b" => "null")
    data = replace(data, r"\bNothing\b" => "null")
    data = replace(data, ": null | Transform" => ": null | ITransform")
    # Drop leftover Julia type assertions in expressions, e.g. `x::Ptr{...}`.
    data = replace(data, r"::[A-Za-z_][A-Za-z0-9_\.]*(?:\{[^}]*\})?" => "")
    # Drop redundant int32 conversion helper in generated TS (any nesting).
    data = strip_safe_int32_convert_calls(data)
    data = strip_uint32_constructor_calls(data)
    # Julia `length(x)` -> TS `x.length` for simple non-nested args.
    data = replace(data, r"\blength\(([^()]+)\)" => s"\1.length")
    # Julia `floor(...)` -> JS `Math.floor(...)`.
    data = replace(data, r"\bfloor\(" => "Math.floor(")
    # Julia `min(...)` -> JS `Math.min(...)` (not `Math.Math.min` — exclude already-prefixed).
    data = replace(data, r"(?<!\bMath\.)\bmin\s*\(" => "Math.min(")
    # Bare `round(...)` -> `Math.round(...)` (word + call only; not `Math.round`, `surround`, etc.).
    data = replace(data, r"(?<!\bMath\.)\bround\s*\(" => "Math.round(")
    # `clamp(...)` stays as `clamp(...)`; generated files import it from `juliaHelpers.ts`.
    # Numeric helpers.
    data = replace(data, r"\bFloat64\(" => "Number(")
    data = replace(data, r"\binv\(([^()]+)\)" => s"(1 / (\1))")
    # Julia tuple literals in value position: `(a, b, c)` -> `[a, b, c]`.
    data = replace(data, r"=\s*\(\s*([^()\n]*,[^()\n]*)\s*\)" => s"= [\1]")
    data = replace(data, r":\s*([A-Za-z_]\w*)\s*=\s*\(\s*([^()\n]*,[^()\n]*)\s*\)" => s": \1 = [\2]")
    # Vector2 / Vector2f / Vector3f constructor calls -> `{ x, y [, z] }` (handles nested parens in arguments).
    data = replace_math_vector_constructor_calls(data)
    # Rigidbody: grounded snap keeps `z` from the integrated position (Julia `Vector2f(x,y)` drops `z` on the Julia side).
    data = replace(
        data,
        "newPosition = {x: newPosition.x, y: currentPosition.y}" =>
            "newPosition = {x: newPosition.x, y: currentPosition.y, z: newPosition.z}",
    )
    # `a && return b` is valid Julia shorthand; TS needs an explicit if.
    data = replace(data, r"(?m)^(\s*)(.+?)\s*&&\s*return\s+(.+)$" => s"\1if (\2) { return \3 }")
    data = replace_return_parenthesized_tuples(data)
    # Julia try/catch forms.
    data = replace(data, r"(?m)^(\s*)try\s*$" => s"\1try {")
    data = replace(data, r"(?m)^(\s*)catch\s+([A-Za-z_]\w*)\s*$" => s"\1} catch (\2) {")
    # Local typed assignment `x::T = ...` -> `let x = ...`.
    data = replace(data, r"(?m)^(\s*)([A-Za-z_]\w*)::[^\s=]+\s*=\s*(.+)$" => s"\1let \2 = \3")
    # Ref cell reads in Julia (`x[]`) become plain property/value access.
    data = replace(data, r"\.r\[\]" => ".r")
    data = replace(data, r"\.g\[\]" => ".g")
    data = replace(data, r"\.b\[\]" => ".b")
    data = replace(data, r"\.a\[\]" => ".a")
    # SDL2 direct calls -> wasm glue calls.
    data = rewrite_sdl_calls_to_glue(data)
    # Common value-shape cleanup.
    data = replace(data, r"let center_world\s*=\s*center_pixels\s*/\s*pixels_per_world_unit\(this\)" => "let center_world = {x: center_pixels.x / pixels_per_world_unit(this), y: center_pixels.y / pixels_per_world_unit(this)}")
    data = replace(data, r"(?m)^(\s*)targetPos\s*=\s*" => s"\1let targetPos = ")
    data = replace(data, r"(?m)^(\s*)targetScale\s*=\s*" => s"\1let targetScale = ")
    data = replace(data, r"\bsetfield\(([^,]+),\s*([^,]+),\s*([^)]+)\)" => s"(\1 as any)[\2 as any] = \3")
    # `@warn "msg"` — string literal only (no interpolated/extra kwargs on this pass).
    data = replace(data, r"@warn\s+\"([^\"]*)\"" => s"console.warn(\"\1\")")
    # error with string literal
    data = replace(data, r"@error\s+\"([^\"]*)\"" => s"console.error(\"\1\")")
    # debug with string literal
    data = replace(data, r"@debug\s+\"([^\"]*)\"" => s"console.debug(\"\1\")")
    # macro invocation style: `@debug("...")`.
    data = replace(data, r"@debug\(" => "console.debug(")
    data = replace(data, r"\bprintln\(" => "console.log(")
    # info with string literal
    data = replace(data, r"@info\s+\"([^\"]*)\"" => s"console.info(\"\1\")")
    return data
end

# `Ref(x)` (Julia box / pointer-ish arg) -> `x`. Out-params and glue calls mutate plain objects in TS.
function strip_ref_wrappers(data::AbstractString)::String
    s = String(data)
    needle = "Ref("
    buf = IOBuffer()
    seg_start = firstindex(s)
    n = lastindex(s)
    while true
        rg = findnext(needle, s, seg_start)
        if rg === nothing
            seg_start <= n && write(buf, SubString(s, seg_start))
            break
        end
        lo = first(rg)
        lo > seg_start && write(buf, SubString(s, seg_start, prevind(s, lo)))
        inner_start = nextind(s, last(rg))
        close_idx = _find_outer_push_close(s, inner_start, n)
        if close_idx === nothing
            write(buf, SubString(s, lo:n))
            break
        end
        inner = s[inner_start:prevind(s, close_idx)]
        write(buf, inner)
        seg_start = nextind(s, close_idx)
    end
    return String(take!(buf))
end

# Julia `x[]` on a Ref -> TS `x`. Skip lowercase names that are TS array element types (`string[]`, …).
function replace_julia_ref_cell_reads(data::AbstractString)::String
    s = String(data)
    pat = r"\b([a-z_$][\w.]*)\[\]"
    io = IOBuffer()
    idx = firstindex(s)
    n = lastindex(s)
    while idx <= n
        rg = findnext(pat, s, idx)
        if rg === nothing
            write(io, SubString(s, idx))
            break
        end
        f = first(rg)
        f > idx && write(io, SubString(s, idx, prevind(s, f)))
        m = match(pat, s, f)
        m === nothing && break
        name = String(m.captures[1])
        write(io, name in TS_ARRAY_PRIMITIVE_TYPE_NAMES ? m.match : name)
        idx = nextind(s, last(rg))
    end
    return String(take!(io))
end

function normalize_julia_ref_for_ts(data::AbstractString)::String
    s = strip_ref_wrappers(data)
    s = replace_julia_ref_cell_reads(s)
    return s
end

function normalize_julgame_global_access(data::AbstractString)::String
    s = String(data)
    # Cleanup old alias-based rewrites from previous converter versions.
    s = replace(s, r"(?m)^var JG = \(globalThis as any\)\.JulGame;\s*\n?" => "")
    s = replace(s, "JG." => "(globalThis as any).JulGame.")
    occursin("JulGame.", s) || return s
    s = replace(s, "JulGame." => "(globalThis as any).JulGame.")
    return s
end

function rewrite_sdl_calls_to_glue(data::AbstractString)::String
    s = String(data)
    # Base mapping: SDL2.SDL_Foo(...) -> JulGameSdl.glue_SDL_Foo(...)
    s = replace(s, r"\bSDL2\.SDL_([A-Za-z0-9_]+)\(" => s"(globalThis as any).JulGameSdl.glue_SDL_\1(")
    # Drop renderer ptr first-arg for calls now routed to glue.
    s = replace(s, r"\b(glue_SDL_[A-Za-z0-9_]+)\(\s*(?:Renderer|\(globalThis as any\)\.JulGame\.Renderer)\s*,\s*" => s"\1(")
    # Flatten SDL_FRect wrapper when used as arg.
    s = replace(s, r"Ref\(SDL2\.SDL_FRect\(([^,]+),\s*([^,]+),\s*([^,]+),\s*([^)]+)\)\)" => s"\1, \2, \3, \4")
    # Normalize Julia 1-based indexing to TS 0-based for any numeric index.
    s = rewrite_one_based_indices(s)
    # Remove temporary color snapshot logic.
    s = replace(s, r"(?m)^\s*(?:\(globalThis as any\)\.JulGameSdl\.)?glue_SDL_GetRenderDrawColor\([^\n]*\)\s*$" => "")
    s = replace(s, r"(?m)^\s*(?:\(globalThis as any\)\.JulGameSdl\.)?glue_SDL_SetRenderDrawColor\(\s*rgba\.r\s*,\s*rgba\.g\s*,\s*rgba\.b\s*,\s*rgba\.a\s*\)\s*;?\s*$" => "")
    s = replace(s, r"(?m)^\s*let rgba = .*Ref\(UInt8\(.*\)\).*\s*$" => "")
    # RenderDrawBlendMode variant currently modeled as blend-only glue.
    s = replace(s, r"(?m)^\s*\(globalThis as any\)\.JulGameSdl\.glue_SDL_SetRenderDrawBlendMode\([^\n]*\)\s*$" => "(globalThis as any).JulGameSdl.glue_SDL_SetRenderDrawBlendMode_BLEND()")
    return s
end

function replace_setfield_calls(data::AbstractString)::String
    s = String(data)
    s = replace(s, r"\bsetfield\(\s*this\s*,\s*([A-Za-z_]\w*)\s*,\s*([^)]+)\)" => s"(this as any)[\1 as any] = \2")
    return s
end

function rewrite_one_based_indices(s::AbstractString)::String
    text = String(s)
    pat = r"\b([A-Za-z_][A-Za-z0-9_\.]*)\[(\d+)\]"
    io = IOBuffer()
    idx = firstindex(text)
    n = lastindex(text)
    while idx <= n
        rg = findnext(pat, text, idx)
        if rg === nothing
            write(io, SubString(text, idx))
            break
        end
        f = first(rg)
        f > idx && write(io, SubString(text, idx, prevind(text, f)))
        m = match(pat, text, f)
        m === nothing && break
        base = String(m[1])
        parsed = tryparse(Int, String(m[2]))
        if parsed === nothing || parsed < 1
            write(io, String(m.match))
        else
            write(io, string(base, "[", parsed - 1, "]"))
        end
        idx = nextind(text, last(rg))
    end
    return String(take!(io))
end

# Avoid collision with DOM/Web Animation types in TS output.
function replace_animation_symbol(data::AbstractString)::String
    s = String(data)
    s = replace(s, r"\bclass\s+Animation\b" => "class JulGameAnimation")
    s = replace(s, r"\bAnimation\[\]" => "JulGameAnimation[]")
    s = replace(s, r"\bAnimation\(" => "JulGameAnimation(")
    return s
end

function replace_imports_usings_includes(data::AbstractString)
    # Comment-out `using` lines; `\1` is the captured match (SubstitutionString).
    data = replace(data, r"(using .*)" => s"// \1")
    data = replace(data, r"(import .*)" => s"// \1")
    lines = split(String(data), '\n'; keepempty = true)
    data = join(
        map(lines) do line
            occursin(r"^\s*include\s*\(", line) ? replace(line, r"^(\s*)" => s"\1// ") : line
        end,
        '\n',
    )
    return data
end

function replace_mutable_structs(data::AbstractString)
    # `mutable struct Name` / `mutable struct Name <: Base` -> TS class (+ optional extends)
    data = replace(
        data,
        r"mutable struct\s+(\w+)\s*<:\s*([A-Za-z_][\w\.]*)" => s"class \1 extends \2 {",
    )
    data = replace(data, r"mutable struct\s+(\w+)" => s"class \1 {")
    return data
end

function replace_structs(data::AbstractString)
    # `struct Name` / `struct Name <: Base` -> TS class (+ optional extends)
    data = replace(
        data,
        r"struct\s+(\w+)\s*<:\s*([A-Za-z_][\w\.]*)" => s"class \1 extends \2 {",
    )
    data = replace(data, r"struct\s+(\w+)" => s"class \1 {")
    return data
end

# Split by commas at top level, ignoring commas inside `{...}`.
function split_top_level_commas(s::AbstractString)::Vector{String}
    out = String[]
    part = IOBuffer()
    depth = 0
    for c in String(s)
        if c == '{'
            depth += 1
            write(part, c)
        elseif c == '}'
            depth -= 1
            write(part, c)
        elseif c == ',' && depth == 0
            push!(out, strip(String(take!(part))))
        else
            write(part, c)
        end
    end
    push!(out, strip(String(take!(part))))
    return out
end

# Split by commas at depth 0; respects `()`, `[]`, `{}`, and `"..."`.
function split_top_level_commas_general(s::AbstractString)::Vector{String}
    s = String(s)
    out = String[]
    part = IOBuffer()
    paren = 0
    bracket = 0
    brace = 0
    i = firstindex(s)
    n = lastindex(s)
    while i <= n
        c = s[i]
        if c == '"'
            endq = _skip_double_quoted_string(s, i, n)
            write(part, SubString(s, i:endq))
            i = nextind(s, endq)
            continue
        end
        if c == '('
            paren += 1
            write(part, c)
        elseif c == ')'
            paren -= 1
            write(part, c)
        elseif c == '['
            bracket += 1
            write(part, c)
        elseif c == ']'
            bracket -= 1
            write(part, c)
        elseif c == '{'
            brace += 1
            write(part, c)
        elseif c == '}'
            brace -= 1
            write(part, c)
        elseif c == ',' && paren == 0 && bracket == 0 && brace == 0
            push!(out, strip(String(take!(part))))
        else
            write(part, c)
        end
        i = nextind(s, i)
    end
    push!(out, strip(String(take!(part))))
    return out
end

function _strip_one_outer_paren_pair(r::AbstractString)::Union{Nothing,String}
    t = strip(String(r))
    fi = firstindex(t)
    li = lastindex(t)
    t[fi] != '(' && return nothing
    t[li] != ')' && return nothing
    inner = t[nextind(t, fi):prevind(t, li)]
    return String(strip(inner))
end

function scalar_type_to_ts(t::AbstractString, scalar_map::Dict{String,String})::String
    t = String(strip(t))
    t == "Ptr{Nothing}" && return "null"
    if startswith(t, "Vector{") && endswith(t, "}")
        inner = t[nextind(t, firstindex(t), 7):prevind(t, lastindex(t))]
        return vector_inner_to_ts(inner, scalar_map)
    end
    if haskey(scalar_map, t)
        return scalar_map[t]
    end
    if occursin('.', t)
        leaf = String(split(t, '.')[end])
        return string(get(scalar_map, leaf, leaf))
    end
    return string(get(scalar_map, t, t))
end

# `::Union{A, B, Ptr{Nothing}}` → `: A | B | null` (brace-balanced).
function replace_union_annotations(data::AbstractString, scalar_map::Dict{String,String})::String
    s = String(data)
    needle = "::Union{"
    io = IOBuffer()
    idx = firstindex(s)
    n = lastindex(s)
    while idx <= n
        rg = findnext(needle, s, idx)
        if rg === nothing
            write(io, SubString(s, idx))
            break
        end
        lo = first(rg)
        brace_open = last(rg)
        lo > idx && write(io, SubString(s, idx, prevind(s, lo)))
        depth = 1
        p = nextind(s, brace_open)
        while p <= n && depth > 0
            c = s[p]
            if c == '{'
                depth += 1
            elseif c == '}'
                depth -= 1
            end
            p = nextind(s, p)
        end
        union_inner = s[nextind(s, brace_open):prevind(s, prevind(s, p))]
        members = split_top_level_commas(union_inner)
        ts_members = map(m -> scalar_type_to_ts(m, scalar_map), members)
        write(io, ": ", join(ts_members, " | "))
        idx = p
    end
    return String(take!(io))
end

function vector_inner_to_ts(inner::AbstractString, scalar_map::Dict{String,String})::String
    inner = String(strip(inner))
    if haskey(scalar_map, inner)
        return scalar_map[inner] * "[]"
    end
    if occursin('.', inner)
        leaf = String(split(inner, '.')[end])
        return string(get(scalar_map, leaf, leaf)) * "[]"
    end
    return string(get(scalar_map, inner, inner)) * "[]"
end

function replace_empty_vector_literals(data::AbstractString)::String
    s = String(data)
    s = replace(s, "Vector2f()" => "{x: 0, y: 0}")
    s = replace(s, "Vector3f()" => "{x: 0, y: 0, z: 0}")
    s = replace(s, "Vector4()" => "{x: 0, y: 0, z: 0, t: 0}")
    s = replace(s, "Vector2()" => "{x: 0, y: 0}")
    s = replace(s, "Vector3()" => "{x: 0, y: 0, z: 0}")
    s = replace(s, "Vector4()" => "{x: 0, y: 0, z: 0, t: 0}")
    # Value-position typed empty array default (`foo: Bar[] = Bar[]`) -> `foo: Bar[] = []`.
    # Keep type annotations intact; only rewrite RHS when the value ends there (param/list terminator),
    # so ref reads like `result[].w` are untouched.
    s = replace(s, r"=\s*[A-Za-z_][A-Za-z0-9_\.]*\[\](?=\s*(?:[,)\n]|$))" => "= []")
    return s
end

function julia_type_expr_to_ts(t::AbstractString, scalar_map::Dict{String,String})::String
    t = String(strip(t))
    t == "Ptr{Nothing}" && return "null"
    t == "Nothing" && return "null"
    startswith(t, "Vector{") && endswith(t, "}") && return vector_inner_to_ts(t[nextind(t, firstindex(t), 7):prevind(t, lastindex(t))], scalar_map)
    if startswith(t, "Union{") && endswith(t, "}")
        inner = t[nextind(t, firstindex(t), 6):prevind(t, lastindex(t))]
        members = split_top_level_commas(inner)
        return join(map(m -> julia_type_expr_to_ts(m, scalar_map), members), " | ")
    end
    if startswith(t, "NTuple{") && endswith(t, "}")
        inner = t[nextind(t, firstindex(t), 7):prevind(t, lastindex(t))]
        parts = split_top_level_commas(inner)
        if length(parts) == 2
            n = tryparse(Int, strip(parts[1]))
            item_ts = julia_type_expr_to_ts(parts[2], scalar_map)
            n !== nothing && n >= 1 && n <= 16 && return "[" * join(fill(item_ts, n), ", ") * "]"
            return item_ts * "[]"
        end
    end
    if haskey(scalar_map, t)
        return scalar_map[t]
    end
    if occursin('.', t)
        leaf = String(split(t, '.')[end])
        return string(get(scalar_map, leaf, leaf))
    end
    return string(get(scalar_map, t, t))
end

function replace_struct_field_annotations(data::AbstractString, scalar_map::Dict{String,String})::String
    lines = split(String(data), '\n'; keepempty = true)
    pat = r"^(\s*[A-Za-z_]\w*)::\s*([^\n=]+?)\s*$"
    out = map(lines) do line
        m = match(pat, line)
        m === nothing && return line
        string(m[1], ": ", julia_type_expr_to_ts(String(m[2]), scalar_map))
    end
    return join(out, '\n')
end

function replace_header_param_annotations(data::AbstractString, scalar_map::Dict{String,String})::String
    lines = split(String(data), '\n'; keepempty = true)
    header_pat = r"^(\s*(?:function\s+[^\s(]+|constructor)\s*\()([^)]*)(\).*)$"
    out = map(lines) do line
        hm = match(header_pat, line)
        hm === nothing && return line
        params = split(String(hm[2]), ',')
        rewritten = map(params) do p
            pm = match(r"^(\s*[A-Za-z_]\w*)::\s*([^=]+?)(\s*=\s*.*)?\s*$", String(p))
            pm === nothing && return p
            name = String(pm[1])
            typ = julia_type_expr_to_ts(String(pm[2]), scalar_map)
            defaultv = pm[3] === nothing ? "" : String(pm[3])
            defaultv = replace(defaultv, r"=\s*nothing\b" => "= null")
            string(name, ": ", typ, defaultv)
        end
        string(hm[1], join(rewritten, ", "), hm[3])
    end
    return join(out, '\n')
end

# `::Vector{Inner}` → `: ts[]` using scalar_map for bare names and the last segment for `Mod.Type`.
# Nested `Vector{Vector{Int}}` is not supported (single `[^}]+` capture).
function replace_vector_annotations(data::AbstractString, scalar_map::Dict{String,String})
    s = String(data)
    pat = r"::Vector\{([^}]+)\}"
    io = IOBuffer()
    idx = firstindex(s)
    n = lastindex(s)
    while idx <= n
        rg = findnext(pat, s, idx)
        if rg === nothing
            write(io, SubString(s, idx))
            break
        end
        f = first(rg)
        f > idx && write(io, SubString(s, idx, prevind(s, f)))
        m = match(pat, s, f)
        m === nothing && break
        inner = m[1]::AbstractString
        write(io, ": ", vector_inner_to_ts(inner, scalar_map))
        idx = nextind(s, last(rg))
    end
    return String(take!(io))
end

function replace_types(data::AbstractString)
    data = replace(data, "Math." => "")
    scalar_map = Dict{String,String}(
        "Int32" => "number",
        "UInt64" => "number",
        "UInt32" => "number",
        "UInt16" => "number",
        "UInt8" => "number",
        "Int64" => "number",
        "Int16" => "number",
        "Int8" => "number",
        "Float32" => "number",
        "Float64" => "number",
        "String" => "string",
        "Bool" => "boolean",
        "Symbol" => "symbol",
        "InternalAnimator" => "InternalAnimator",
        "InternalSprite" => "InternalSprite",
        "InternalShape" => "InternalShape",
        "InternalRigidbody" => "InternalRigidbody",
        "InternalSoundSource" => "InternalSoundSource",
        "InternalSprite" => "InternalSprite",
        "InternalShape" => "InternalShape",
        "InternalRigidbody" => "InternalRigidbody",
        "InternalSoundSource" => "InternalSoundSource",
        "Int" => "number",
        "Animation" => "JulGameAnimation",
        "Transform" => "ITransform",
        "Any" => "any",
    )
    data = replace_union_annotations(data, scalar_map)
    data = replace_vector_annotations(data, scalar_map)
    data = replace_struct_field_annotations(data, scalar_map)
    data = replace_header_param_annotations(data, scalar_map)
    # Longer keys first so `::Int` does not chew `::Int32` into `: number` + `32`.
    for k in sort(collect(keys(scalar_map)), by = length, rev = true)
        data = replace(data, "::$k" => ": $(scalar_map[k])")
    end
    return data
end

function replace_constructor(data::AbstractString)
    # Julia inner ctor is `function ClassName(args)` (no `{`). Only the ctor whose name
    # matches a `class Name {` in this file becomes `constructor(args)`.
    seen = Set{String}()
    for m in eachmatch(r"class\s+(\w+)\s*\{", data)
        name = m.captures[1]::AbstractString
        name in seen && continue
        push!(seen, name)
        # `name` comes from `(\w+)` on the class line — no regex metacharacters to escape.
        pat = Regex("function\\s+" * string(name) * "\\s*\\(")
        data = replace(data, pat => "constructor(")
    end
    # TS needs `{` before the body; do this line-wise so nested `)` in defaults do not break.
    lines = split(String(data), '\n'; keepempty = true)
    lines = map(lines) do line
        startswith(strip(line), "constructor(") || return line
        occursin('{', line) && return line
        return line * " {"
    end
    data = join(lines, '\n')

    data = replace(data, "this = new()" => "")
    # Only the ctor idiom `return this` on its own line — not `return this.foo`.
    data = replace(data, r"(?m)^\s*return this\s*$" => "")
    return data
end

# `function A.B.c(` → `function A_B_c(` — TS cannot use `.` in a `function` name.
# Uses `findnext` + `match` (no `replace(str, regex, f)` — that overload is newer Julia).
function replace_function_declaration_dots(data::AbstractString)
    s = String(data)
    pat = r"(?m)^(\s*function\s+)([^\s(]+)(\()"
    io = IOBuffer()
    idx = firstindex(s)
    n = lastindex(s)
    while idx <= n
        rg = findnext(pat, s, idx)
        if rg === nothing
            write(io, SubString(s, idx))
            break
        end
        f = first(rg)
        f > idx && write(io, SubString(s, idx, prevind(s, f)))
        m = match(pat, s, f)
        m === nothing && break
        write(io, string(m[1], replace(m[2], "." => "_"), m[3]))
        idx = nextind(s, last(rg))
    end
    return String(take!(io))
end

# `Component.foo(` → `Component_foo(` so calls match mangled declarations.
function replace_component_qualified_calls(data::AbstractString)
    replace(data, r"\bComponent\.(\w+)\s*\(" => s"Component_\1(")
end

function replace_function_definitions(data::AbstractString)
    data = replace(data, r"@inline\s+" => "")
    # Julia: `function name(args)` then newline — TS needs `{`. Must balance `()` so defaults like
    # `f = g(...)` do not terminate the match early (the old `[^)]*` broke nested parens).
    lines = split(String(data), '\n'; keepempty = true)
    out = map(add_brace_to_function_line, lines)
    return join(out, '\n')
end

function add_brace_to_function_line(line::AbstractString)::String
    occursin('{', line) && return String(line)
    s = String(line)
    startswith(strip(s), "constructor(") && return s
    occursin(r"^\s*function\s+", s) || return s
    open_paren = findfirst('(', s)
    open_paren === nothing && return s
    depth = 0
    i = first(open_paren)
    n = lastindex(s)
    while i <= n
        c = s[i]
        if c == '('
            depth += 1
        elseif c == ')'
            depth -= 1
            if depth == 0
                tail = String(SubString(s, nextind(s, i)))
                t = strip(tail)
                if isempty(t) || startswith(t, "//") || startswith(t, "#")
                    return string(SubString(s, 1, i), " {")
                end
                return s
            end
        end
        i = nextind(s, i)
    end
    return s
end

# Trailing `// ...` on the same line as a condition (from Julia `# ...` after `replace_comments`).
function _split_trailing_ts_comment(s::AbstractString)::Tuple{String, String}
    t = String(s)
    r = findlast(" // ", t)
    if r === nothing
        return String(strip(t)), ""
    end
    lo = first(r)
    pre = lo <= 1 ? "" : String(strip(t[1:prevind(t, lo)]))
    suf = String(t[lo:end])
    return pre, suf
end

# Julia `else` / `elseif` — close the previous `if` arm and open the next (after `replace_if_statements` added `{`).
function replace_else_elseif_blocks(data::AbstractString)::String
    lines = split(String(data), '\n'; keepempty = true)
    already = r"^\s*\}\s*else\b"
    pat_else = r"^(\s*)else\b(.*)$"
    pat_elseif = r"^(\s*)elseif\b\s+(.+)$"
    return join(
        map(lines) do line
            occursin(already, line) && return line
            m = match(pat_else, line)
            if m !== nothing
                tail = String(m[2])
                occursin(r"^\s*(?://[^\n]*)?\s*$", tail) || return line
                return string(m[1], "} else {", tail)
            end
            m = match(pat_elseif, line)
            if m !== nothing
                raw = String(m[2])
                cond, cmt = _split_trailing_ts_comment(raw)
                cond = String(strip(cond))
                if startswith(cond, "(") && endswith(cond, ")")
                    cond = String(strip(chop(cond, head = 1, tail = 1)))
                end
                return string(m[1], "} else if (", cond, ") {", cmt)
            end
            return line
        end,
        '\n',
    )
end

# `for x in xs` → `for (const x of xs) {` (line-wise; body closing stays `}` from Julia `end`).
function replace_for_in_loops(data::AbstractString)::String
    lines = split(String(data), '\n'; keepempty = true)
    pat = r"^(\s*)for\s+([A-Za-z_]\w*)\s+in\s+(.+)$"
    out = map(lines) do line
        m = match(pat, line)
        m === nothing && return line
        string(m[1], "for (const ", m[2], " of ", strip(String(m[3])), ") {")
    end
    return join(out, '\n')
end

function replace_if_statements(data::AbstractString)
    # Julia: `if cond` / `if(cond)` — TS: `if (cond) {`. Trailing line comment preserved after `{`.
    s = String(data)
    lines = split(s, '\n'; keepempty = true)
    done_line = r"^\s*if\s*\([^)]*\)\s*\{\s*$"
    pat = r"^(\s*)if\b\s*(.+)$"
    return join(
        map(lines) do line
            occursin(done_line, line) && return line
            m = match(pat, line)
            if m === nothing
                line
            else
                raw = String(m[2])
                cond, cmt = _split_trailing_ts_comment(raw)
                cond = String(strip(cond))
                if startswith(cond, "(") && endswith(cond, ")")
                    cond = String(strip(chop(cond, head = 1, tail = 1)))
                end
                string(m[1], "if (", cond, ") {", cmt)
            end
        end,
        '\n',
    )
end

function replace_first_assignments_with_let(data::AbstractString)::String
    lines = split(String(data), '\n'; keepempty = true)
    seen = Set{String}()
    pat = r"^(\s*)([A-Za-z_]\w*)\s*=\s*(.+)$"
    header_pat = r"^\s*(?:function\s+[^\s(]+|constructor)\s*\(([^)]*)\)"
    out = map(lines) do line
        hm = match(header_pat, line)
        if hm !== nothing
            params = split(String(hm[1]), ',')
            for p in params
                pm = match(r"^\s*([A-Za-z_]\w*)", p)
                pm === nothing && continue
                push!(seen, String(pm[1]))
            end
            return line
        end
        m = match(pat, line)
        m === nothing && return line
        indent = String(m[1])
        name = String(m[2])
        rhs = String(m[3])
        # Skip obvious non-declarations / already-TS declarations.
        startswith(rhs, "=") && return line  # `==`, `===`
        startswith(rhs, ">") && return line  # `=>`
        startswith(rhs, "<") && return line  # `=<` / malformed cases
        startswith(name, "this") && return line
        if name in seen
            return line
        end
        push!(seen, name)
        return string(indent, "let ", name, " = ", rhs)
    end
    return join(out, '\n')
end

function custom_function_removal(data::AbstractString)
    functions_to_remove = [
        "Component_update_array_value",
        "Component_append_array",
        "Component_get_type",

        # MainLoop

        # Transform
        "on_notify",

        "Base.setproperty!",
    ]
    s = String(data)
    for func in functions_to_remove
        s = remove_ts_function_block(s, func)
    end
    return s
end

# Strip a whole `function name(...) { ... }` (names are already TS/mangled). `r"...$var"` does not interpolate.
function remove_ts_function_block(s::String, func::AbstractString)::String
    pat = Regex("(?m)^\\s*function\\s+" * func * "\\s*\\([^)]*\\)\\s*\\{")
    while true
        rg = findfirst(pat, s)
        rg === nothing && return s
        lo = first(rg)
        hi = last(rg)  # `{` that opens the body

        depth = 1
        p = nextind(s, hi)
        n = lastindex(s)
        while p <= n && depth > 0
            c = s[p]
            if c == '{'
                depth += 1
            elseif c == '}'
                depth -= 1
            end
            p = nextind(s, p)
        end

        fi = firstindex(s)
        prefix = lo > fi ? s[fi:prevind(s, lo)] : ""
        suffix = p <= n ? s[p:n] : ""
        s = string(prefix, suffix)
    end
end

# Julia named-tuple / kwargs call shape `a=x, b=y` → TS single-arg object `{ a: x, b: y }` (shorthand when `a==x`).
function _named_julia_kwargs_to_ts_object(inner::AbstractString)::Union{Nothing,String}
    t = String(strip(inner))
    isempty(t) && return nothing
    occursin('=', t) || return nothing
    parts = split_top_level_commas_general(t)
    props = String[]
    for p in parts
        pt = String(strip(p))
        pm = match(r"^([A-Za-z_]\w*)\s*=\s*(.+)$", pt)
        pm === nothing && return nothing
        k = String(pm[1])
        v = String(strip(String(pm[2])))
        if v == k
            push!(props, k)
        else
            push!(props, string(k, ": ", v))
        end
    end
    isempty(props) && return nothing
    return string("{ ", join(props, ", "), " }")
end

# Convert calls whose entire argument list is `name=value` pairs (no positional args).
function replace_keyword_style_calls_to_object_args(data::AbstractString)::String
    s = String(data)
    out = IOBuffer()
    i = firstindex(s)
    n = lastindex(s)
    pat_call = r"\b([A-Za-z_]\w*)\("
    while i <= n
        rg = findnext(pat_call, s, i)
        if rg === nothing
            write(out, SubString(s, i:n))
            break
        end
        lo = first(rg)
        lo > i && write(out, SubString(s, i, prevind(s, lo)))
        m = match(pat_call, s, lo)
        m === nothing && (write(out, s[lo]); i = nextind(s, lo); continue)
        fname = String(m.captures[1])
        open_paren = last(rg)
        close_idx = _find_outer_push_close(s, open_paren, n)
        if close_idx === nothing
            write(out, SubString(s, lo:lo))
            i = nextind(s, lo)
            continue
        end
        inner = s[nextind(s, open_paren):prevind(s, close_idx)]
        obj = _named_julia_kwargs_to_ts_object(inner)
        if obj !== nothing
            write(out, fname, "(", obj, ")")
            i = nextind(s, close_idx)
        else
            write(out, SubString(s, lo:close_idx))
            i = nextind(s, close_idx)
        end
    end
    return String(take!(out))
end

# `Base.invokelatest(f)` → `f()`; `Base.invokelatest(f, a, b)` → `f(a, b)`;
# `Base.invokelatest(f, (a=x, b=y))` → `f({ a: x, b: y })` (TS options object, not fake keyword args).
function replace_invokelatest_calls(data::AbstractString)::String
    s = String(data)
    needle = "Base.invokelatest("
    buf = IOBuffer()
    seg_start = firstindex(s)
    n = lastindex(s)
    while true
        rg = findnext(needle, s, seg_start)
        if rg === nothing
            seg_start <= n && write(buf, SubString(s, seg_start))
            break
        end
        lo = first(rg)
        lo > seg_start && write(buf, SubString(s, seg_start, prevind(s, lo)))
        inner_start = nextind(s, last(rg))
        close_idx = _find_outer_push_close(s, inner_start, n)
        if close_idx === nothing
            write(buf, SubString(s, lo:n))
            break
        end
        inner = s[inner_start:prevind(s, close_idx)]
        parts = split_top_level_commas_general(inner)
        callee = isempty(parts) ? "" : strip(parts[1])
        if isempty(callee)
            write(buf, SubString(s, lo:close_idx))
            seg_start = nextind(s, close_idx)
            continue
        end
        replacement =
            if length(parts) == 1
                string(callee, "()")
            else
                rest = map(strip, parts[2:end])
                arg_inner =
                    if length(rest) == 1
                        u = _strip_one_outer_paren_pair(rest[1])
                        core = u === nothing ? rest[1] : u
                        obj = _named_julia_kwargs_to_ts_object(core)
                        obj === nothing ? core : obj
                    else
                        mapped = map(rest) do seg
                            seg = String(strip(seg))
                            u = _strip_one_outer_paren_pair(seg)
                            core = u === nothing ? seg : u
                            obj = _named_julia_kwargs_to_ts_object(core)
                            obj === nothing ? seg : obj
                        end
                        join(mapped, ", ")
                    end
                string(callee, "(", arg_inner, ")")
            end
        write(buf, replacement)
        seg_start = nextind(s, close_idx)
    end
    return String(take!(buf))
end

# `push!(collection, item)` → `collection.push(item)` (balanced parens/brackets; skips `"..."` segments).
function replace_push_calls(data::AbstractString)::String
    s = String(data)
    needle = "push!("
    buf = IOBuffer()
    seg_start = firstindex(s)
    n = lastindex(s)
    while true
        rg = findnext(needle, s, seg_start)
        if rg === nothing
            seg_start <= n && write(buf, SubString(s, seg_start))
            break
        end
        lo = first(rg)
        lo > seg_start && write(buf, SubString(s, seg_start, prevind(s, lo)))
        inner_start = nextind(s, last(rg))
        res = _parse_push_two_args(s, inner_start, n)
        if res === nothing
            close_idx = _find_outer_push_close(s, inner_start, n)
            if close_idx === nothing
                write(buf, SubString(s, lo:n))
                break
            end
            write(buf, SubString(s, lo:close_idx))
            seg_start = nextind(s, close_idx)
            continue
        end
        arg1, arg2, close_idx = res
        write(buf, strip(String(arg1)), ".push(", strip(String(arg2)), ")")
        seg_start = nextind(s, close_idx)
    end
    return String(take!(buf))
end

function _find_outer_push_close(s::String, inner_start::Int, n::Int)::Union{Nothing, Int}
    i = inner_start
    paren = 1
    bracket = 0
    brace = 0
    while i <= n
        c = s[i]
        if c == '"'
            i = _skip_double_quoted_string(s, i, n)
            i > n && return nothing
            i = nextind(s, i)
            continue
        end
        if c == '('
            paren += 1
        elseif c == ')'
            paren -= 1
            if paren == 0
                return i
            end
        elseif c == '['
            bracket += 1
        elseif c == ']'
            bracket -= 1
        elseif c == '{'
            brace += 1
        elseif c == '}'
            brace -= 1
        end
        i = nextind(s, i)
    end
    return nothing
end

function _skip_double_quoted_string(s::String, open_quote_at::Int, n::Int)::Int
    i = nextind(s, open_quote_at)
    while i <= n
        c = s[i]
        if c == '\\'
            i = nextind(s, i)
            i = nextind(s, i)
            continue
        end
        if c == '"'
            return i
        end
        i = nextind(s, i)
    end
    return i
end

function _parse_push_two_args(s::String, inner_start::Int, n::Int)::Union{Nothing, Tuple{SubString{String}, SubString{String}, Int}}
    i = inner_start
    paren = 1
    bracket = 0
    brace = 0
    arg1_lo = i
    split_at = nothing
    while i <= n
        c = s[i]
        if c == '"'
            i = _skip_double_quoted_string(s, i, n)
            i > n && return nothing
            i = nextind(s, i)
            continue
        end
        if c == '('
            paren += 1
        elseif c == ')'
            paren -= 1
            if paren == 0
                return nothing
            end
        elseif c == '['
            bracket += 1
        elseif c == ']'
            bracket -= 1
        elseif c == '{'
            brace += 1
        elseif c == '}'
            brace -= 1
        elseif c == ',' && paren == 1 && bracket == 0 && brace == 0
            split_at = i
            break
        end
        i = nextind(s, i)
    end
    split_at === nothing && return nothing
    arg1 = SubString(s, arg1_lo, prevind(s, split_at))
    i = nextind(s, split_at)
    arg2_lo = i
    while i <= n
        c = s[i]
        if c == '"'
            i = _skip_double_quoted_string(s, i, n)
            i > n && return nothing
            i = nextind(s, i)
            continue
        end
        if c == '('
            paren += 1
        elseif c == ')'
            paren -= 1
            if paren == 0
                arg2 = SubString(s, arg2_lo, prevind(s, i))
                return (arg1, arg2, i)
            end
        elseif c == '['
            bracket += 1
        elseif c == ']'
            bracket -= 1
        elseif c == '{'
            brace += 1
        elseif c == '}'
            brace -= 1
        end
        i = nextind(s, i)
    end
    return nothing
end

function remove_!_from_function_names(data::AbstractString)
    return replace(data, "!(" => "(")
end

function source_files_from_manifest(; repo_root::AbstractString = REPO_ROOT)::Vector{String}
    manifest = joinpath(repo_root, "ts", "files-needed.txt")
    isfile(manifest) || return String[]
    wanted = String[]
    for raw in split(read(manifest, String), '\n')
        name = strip(raw)
        isempty(name) && continue
        push!(wanted, endswith(name, ".jl") ? name : name * ".jl")
    end

    # Build basename -> absolute file map once from src/.
    by_name = Dict{String, Vector{String}}()
    src_root = joinpath(repo_root, "src")
    for (dir, _, files) in walkdir(src_root)
        for f in files
            !endswith(f, ".jl") && continue
            abs = joinpath(dir, f)
            if haskey(by_name, f)
                push!(by_name[f], abs)
            else
                by_name[f] = [abs]
            end
        end
    end

    selected = String[]
    for name in wanted
        matches = get(by_name, name, String[])
        isempty(matches) && error("files-needed entry not found in src/: $name")
        length(matches) > 1 && error("files-needed entry is ambiguous in src/: $name")
        push!(selected, first(matches))
    end
    return selected
end

function replace_entire_line_if_matches(data::AbstractString)::String
    # Ordered rules: first match wins. If `needle` appears anywhere on a line, the whole line becomes `replacement`.
    # Use a substring needle for literals; switch to `needle isa Regex` + `occursin(needle, line)` if you need `\b` word boundaries.
    line_rules = Pair{Union{String, Regex}, String}[
        "add_observer" => "",
    ]
    lines = split(String(data), '\n'; keepempty = true)
    out = map(lines) do line
        for (needle, replacement) in line_rules
            occursin(needle, line) && return String(replacement)
        end
        line
    end
    return join(out, '\n')
end

function main()
    files = source_files_from_manifest()
    isempty(files) && (files = [joinpath(REPO_ROOT, "src", "MainLoop.jl")])
    # Smallest-first helps us iterate patterns safely from simpler files upward.
    sort!(files, by = f -> filesize(f))
    mkpath(default_out_dir())
    for f in files
        isfile(f) || error("not a file: $f")
        println(transpile_file(f))
    end
end

main()
