#!/usr/bin/env julia
# Julia → TypeScript stub emitter (extend later).
#
#   julia convert.jl
#
# Output path rule: <REPO_ROOT>/_generated/<mirror-of-relative-path>.ts

const REPO_ROOT = normpath(joinpath(@__DIR__, ".."))

default_out_dir() = joinpath(REPO_ROOT, "_generated")

"""
    ts_output_path(jl_path; repo_root, generated_dir)

Build the `.ts` path as: `joinpath(repo_root, generated_dir, <same relative dirs as jl_path>, <stem>.ts)`.

Example: `repo/src/engine/Foo.jl` → `repo/_generated/src/engine/Foo.ts`

You cannot “edit” a `joinpath` result in place — strings are immutable. Split with `splitdir` / `relpath`, then `joinpath` again.
"""
function ts_output_path(
    jl_path::AbstractString;
    repo_root::AbstractString = REPO_ROOT,
    generated_dir::AbstractString = "_generated",
)::String
    abs_jl = abspath(jl_path)
    abs_root = abspath(repo_root)
    rel = try
        relpath(abs_jl, abs_root)
    catch
        splitdir(abs_jl)[2]  # basename-only fallback
    end
    rel_dir, rel_file = splitdir(rel)
    stem = splitext(rel_file)[1]
    isempty(rel_dir) && return joinpath(abs_root, generated_dir, stem * ".ts")
    joinpath(abs_root, generated_dir, rel_dir, stem * ".ts")
end

function emit_stub(path_ts::AbstractString, path_jl::AbstractString)
    mkpath(dirname(path_ts))
    rel = try
        relpath(path_jl, REPO_ROOT)
    catch
        path_jl
    end
    open(path_ts, "w") do io
        println(io, "// Generated by tools/convert.jl from ", rel)
        println(io, "// Stub: transpiler not implemented for this file.")
        println(io, "export {}")
    end
    path_ts
end

function transpile_file(path_jl::AbstractString)
    path_ts = ts_output_path(path_jl)
    emit_stub(path_ts, path_jl)
    parse_file(path_jl, path_ts)
end

function parse_file(path_jl::AbstractString, path_ts::AbstractString)
    mkpath(dirname(path_ts))
    data = read(path_jl, String)
    data = replace_module(data)
    data = replace_end(data)
    data = replace_exports(data)
    data = replace_comments(data)
    data = replace_imports_usings(data)
    data = replace_mutable_structs(data)
    data = replace_types(data)
    data = replace_constructor(data)
    data = replace_function_declaration_dots(data)
    data = replace_component_qualified_calls(data)
    data = replace_function_definitions(data)
    data = replace_if_statements(data)
    data = custom_function_removal(data)
    open(path_ts, "w") do io
        print(io, data)
    end
    path_ts
end

function replace_module(data::AbstractString)
    # replace the line with module with empty string
    data = replace(data, r"module .*" => "")
    # `findlast("end", s)` returns a `UnitRange` of indices, not one integer
    r = findlast("end", data)
    r === nothing && return data
    head = data[1:prevind(data, first(r))]
    return head * ""
end

function replace_end(data::AbstractString)
    # Julia block closer only: plain `r"end"` would mangle identifiers like `append_*`.
    data = replace(data, r"\bend\b" => "}")
    return data
end

function replace_exports(data::AbstractString)
    # replace the line with export with empty string
    data = replace(data, r"export .*" => "")
    return data
end

function replace_comments(data::AbstractString)
    # replace the line with # with empty string
    data = replace(data, r"#" => "//")
    return data
end

function replace_imports_usings(data::AbstractString)
    # Comment-out `using` lines; `\1` is the captured match (SubstitutionString).
    data = replace(data, r"(using .*)" => s"// \1")
    data = replace(data, r"(import .*)" => s"// \1")
    return data
end

function replace_mutable_structs(data::AbstractString)
    # `mutable struct Name` → `class Name {` (must capture `\1` in the regex)
    data = replace(data, r"mutable struct\s+(\w+)" => s"class \1 {")
    return data
end

function replace_types(data::AbstractString)
    type_map = Dict{String, String}(
        "Int32" => "number",
        "Float64" => "number",
        "String" => "string",
        "Bool" => "boolean",
        "Vector{Int32}" => "number[]",
        "Vector{Float64}" => "number[]",
        "Vector{String}" => "string[]",
        "Int" => "number",
        "Animation" => "JulGameAnimation",
        # regexes for Vector{*}:
        "Vector{Math.Vector4}" => "Vector4[]",
    )
    # Longer keys first so `::Int` does not chew `::Int32` into `: number` + `32`.
    for k in sort(collect(keys(type_map)), by = length, rev = true)
        data = replace(data, "::$k" => ": $(type_map[k])")
    end
    return data
end

function replace_constructor(data::AbstractString)
    # Julia inner ctor is `function ClassName(args)` (no `{`). Only the ctor whose name
    # matches a `class Name {` in this file becomes `constructor(args)`.
    seen = Set{String}()
    for m in eachmatch(r"class\s+(\w+)\s*\{", data)
        name = m.captures[1]::AbstractString
        name in seen && continue
        push!(seen, name)
        # `name` comes from `(\w+)` on the class line — no regex metacharacters to escape.
        pat = Regex("function\\s+" * string(name) * "\\s*\\(")
        data = replace(data, pat => "constructor(")
    end
    # TS needs `{` before the body; Julia starts the block on the next line.
    data = replace(data, r"(?m)^(\s*constructor\([^)]*\))\s*$" => s"\1 {")

    data = replace(data, "this = new()" => "")
    data = replace(data, "return this" => "")
    return data
end

# `function A.B.c(` → `function A_B_c(` — TS cannot use `.` in a `function` name.
# Uses `findnext` + `match` (no `replace(str, regex, f)` — that overload is newer Julia).
function replace_function_declaration_dots(data::AbstractString)
    s = String(data)
    pat = r"(?m)^(function\s+)([^\s(]+)(\()"
    io = IOBuffer()
    idx = firstindex(s)
    n = lastindex(s)
    while idx <= n
        rg = findnext(pat, s, idx)
        if rg === nothing
            write(io, SubString(s, idx))
            break
        end
        f = first(rg)
        f > idx && write(io, SubString(s, idx, prevind(s, f)))
        m = match(pat, s, f)
        m === nothing && break
        write(io, string(m[1], replace(m[2], "." => "_"), m[3]))
        idx = nextind(s, last(rg))
    end
    return String(take!(io))
end

# `Component.foo(` → `Component_foo(` so calls match mangled declarations.
function replace_component_qualified_calls(data::AbstractString)
    replace(data, r"\bComponent\.(\w+)\s*\(" => s"Component_\1(")
end

function replace_function_definitions(data::AbstractString)
    # Julia: `function qual_name(args)` then newline — no `{`. TS needs `{` on the same line.
    # Name is `[^\s(]+`; `constructor(...)` is unchanged.
    data = replace(data, r"(?m)^(\s*function\s+[^\s(]+\([^)]*\))\s*$" => s"\1 {")
    return data
end

function replace_if_statements(data::AbstractString)
    # Julia: `if cond` then newline — TS: `if (cond) {`. Single-line condition only; else/elseif later.
    s = String(data)
    lines = split(s, '\n'; keepempty = true)
    done_line = r"^\s*if\s*\([^)]*\)\s*\{\s*$"
    pat = r"^(\s*)if\b\s+(.+)$"
    return join(
        map(lines) do line
            occursin(done_line, line) && return line
            m = match(pat, line)
            m === nothing ? line : string(m[1], "if (", strip(m[2]), ") {")
        end,
        '\n',
    )
end

function custom_function_removal(data::AbstractString)
    functions_to_remove = [
        "Component_update_array_value",
        "Component_append_array",
        "Component_get_type",
    ]
    s = String(data)
    for func in functions_to_remove
        s = remove_ts_function_block(s, func)
    end
    return s
end

# Strip a whole `function name(...) { ... }` (names are already TS/mangled). `r"...$var"` does not interpolate.
function remove_ts_function_block(s::String, func::AbstractString)::String
    pat = Regex("(?m)^\\s*function\\s+" * func * "\\s*\\([^)]*\\)\\s*\\{")
    while true
        rg = findfirst(pat, s)
        rg === nothing && return s
        lo = first(rg)
        hi = last(rg)  # `{` that opens the body

        depth = 1
        p = nextind(s, hi)
        n = lastindex(s)
        while p <= n && depth > 0
            c = s[p]
            if c == '{'
                depth += 1
            elseif c == '}'
                depth -= 1
            end
            p = nextind(s, p)
        end

        fi = firstindex(s)
        prefix = lo > fi ? s[fi:prevind(s, lo)] : ""
        suffix = p <= n ? s[p:n] : ""
        s = string(prefix, suffix)
    end
end

function main()
    files = [joinpath(REPO_ROOT, "src", "engine", "Component", "Animation.jl")]
    mkpath(default_out_dir())
    for f in files
        isfile(f) || error("not a file: $f")
        println(transpile_file(f))
    end
end

main()
